-- ============================================================================
-- Consolidadores por área + visibilidad por ámbito (salidas / rendiciones)
-- ============================================================================
-- ORDEN DE EJECUCIÓN: este script va JUNTO con el despliegue del backend, no
-- antes ni mucho después. El paso 2 RENOMBRA ga_salida_visibilidad_area, así que
-- entre correrlo y desplegar el backend nuevo la visibilidad de Gestión de
-- Salidas queda rota (el código viejo consulta el nombre viejo).
-- ============================================================================

BEGIN;

-- ── 1. Catálogo de ámbitos de visibilidad ───────────────────────────────────
-- La visibilidad por área dejó de ser solo de salidas: Gestión de Rendiciones
-- tiene la suya, independiente. El ámbito es un dato predefinido, así que va en
-- su propia tabla y no como texto en cada fila.
CREATE TABLE IF NOT EXISTS ga_visibilidad_ambito (
    ga_visibilidad_ambito_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     varchar(50)  NOT NULL,
    nombre     varchar(150) NOT NULL,
    orden      integer      NOT NULL DEFAULT 0,
    active     boolean      NOT NULL DEFAULT true,
    state      boolean      NOT NULL DEFAULT true,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_visibilidad_ambito_codigo
    ON ga_visibilidad_ambito (lower(codigo)) WHERE state;

INSERT INTO ga_visibilidad_ambito (ga_visibilidad_ambito_id, codigo, nombre, orden)
VALUES (1, 'SALIDAS',     'Gestión de Salidas',     1),
       (2, 'RENDICIONES', 'Gestión de Rendiciones', 2)
ON CONFLICT (ga_visibilidad_ambito_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('ga_visibilidad_ambito', 'ga_visibilidad_ambito_id'),
    (SELECT max(ga_visibilidad_ambito_id) FROM ga_visibilidad_ambito));

-- ── 2. ga_salida_visibilidad_area → ga_visibilidad_area (+ ámbito) ──────────
-- La tabla es la misma, solo que ahora cubre dos ámbitos. Las filas existentes
-- son todas del ámbito SALIDAS (es lo único que había).
ALTER TABLE ga_salida_visibilidad_area RENAME TO ga_visibilidad_area;
ALTER INDEX ga_salida_visibilidad_area_pkey RENAME TO ga_visibilidad_area_pkey;

ALTER TABLE ga_visibilidad_area
    ADD COLUMN IF NOT EXISTS ambito_id integer NOT NULL DEFAULT 1
        REFERENCES ga_visibilidad_ambito (ga_visibilidad_ambito_id);
-- El default era solo para poblar lo existente: de acá en adelante lo manda el código.
ALTER TABLE ga_visibilidad_area ALTER COLUMN ambito_id DROP DEFAULT;

DROP INDEX IF EXISTS ix_ga_salida_visibilidad_area_worker;
DROP INDEX IF EXISTS ux_ga_salida_visibilidad_area_worker_scope_alive;

CREATE INDEX IF NOT EXISTS ix_ga_visibilidad_area_worker
    ON ga_visibilidad_area (ambito_id, worker_id) WHERE state = true;
CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_visibilidad_area_vivo
    ON ga_visibilidad_area (ambito_id, worker_id, area_scope_id) WHERE state = true;

-- ── 2b. Arrastrar la visibilidad actual al ámbito RENDICIONES ───────────────
-- Hasta hoy una sola asignación recortaba las DOS pantallas. Si no se copia, el que
-- tenía override empieza a resolver Gestión de Rendiciones por el algoritmo y su
-- alcance cambia (hacia arriba o hacia abajo según el caso). Se copia tal cual para
-- que nadie note el cambio; desde ahora cada pantalla se administra por separado y
-- se puede recortar una sin tocar la otra.
INSERT INTO ga_visibilidad_area (ambito_id, worker_id, area_scope_id, incluye_descendientes, created_at, state)
SELECT 2, v.worker_id, v.area_scope_id, v.incluye_descendientes, now(), true
FROM ga_visibilidad_area v
WHERE v.ambito_id = 1 AND v.state
  AND NOT EXISTS (
      SELECT 1 FROM ga_visibilidad_area x
      WHERE x.ambito_id = 2 AND x.state
        AND x.worker_id = v.worker_id AND x.area_scope_id = v.area_scope_id
  );

-- ── 3. Consolidadores por área ──────────────────────────────────────────────
-- Espejo de area_revisores: n consolidadores por nodo (y opcionalmente por
-- proyecto, cuando el área filtra por proyecto). La diferencia está en cómo se
-- leen: en revisores gana el primer activo; acá TODOS los activos son aptos.
CREATE TABLE IF NOT EXISTS area_consolidadores (
    area_consolidadores_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_scope_id   integer NOT NULL REFERENCES area_scope (area_scope_id),
    project_id      integer NULL     REFERENCES project (project_id),
    consolidador_id integer NOT NULL REFERENCES workers (id),
    orden_prioridad integer NOT NULL DEFAULT 1,
    active          boolean NOT NULL DEFAULT true,
    state           boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NULL,
    CONSTRAINT chk_area_consolidadores_prioridad CHECK (orden_prioridad >= 1)
);

CREATE INDEX IF NOT EXISTS ix_area_consolidadores_area
    ON area_consolidadores (area_scope_id) WHERE state = true;
CREATE INDEX IF NOT EXISTS ix_area_consolidadores_proyecto
    ON area_consolidadores (area_scope_id, project_id) WHERE state = true;
CREATE UNIQUE INDEX IF NOT EXISTS ux_area_consolidadores_vivo
    ON area_consolidadores (area_scope_id, project_id, consolidador_id)
    NULLS NOT DISTINCT WHERE state = true;

-- ── 4. Funcionalidades nuevas ───────────────────────────────────────────────
-- Solo las que no existían. Las que se MUDARON de pantalla conservan su
-- feature_key para no perder lo que ya está asignado a cada rol:
--   · configuracion.revisores-areas                     → Solicitud de Salidas · Configuración
--   · gestion-administrativa.config.visibilidad-salidas → Gestión de Salidas · Configuración
-- El module_id se toma de una feature de Gestión Administrativa que ya existe, para
-- no depender de que el id del módulo sea el mismo en dev y en prod.
INSERT INTO feature (feature_key, module_id)
SELECT k.feature_key,
       (SELECT f.module_id FROM feature f WHERE f.feature_key = 'gestion-administrativa.config.correos')
FROM (VALUES
    ('gestion-administrativa.config.visibilidad-rendiciones'),
    ('gestion-administrativa.config.consolidadores-areas')
) AS k(feature_key)
ON CONFLICT (feature_key) DO NOTHING;

-- ADMINISTRADOR DEL SISTEMA (role_id = 1) accede a todo lo nuevo.
INSERT INTO role_feature (role_id, feature_id)
SELECT 1, f.feature_id
FROM feature f
WHERE f.feature_key IN (
    'gestion-administrativa.config.visibilidad-rendiciones',
    'gestion-administrativa.config.consolidadores-areas'
)
ON CONFLICT DO NOTHING;

COMMIT;
