-- ============================================================================
-- Propietarios (app Convivir Abril): tabla propietario + módulo y funcionalidad de la intranet
-- ============================================================================
-- Cada fila es un inmueble de un propietario (person): proyecto, torre y departamento. Una persona
-- con dos departamentos tiene dos filas; un departamento con dos dueños, también. La cuenta con la
-- que entra a la app es la de person.user_id, con el rol PROPIETARIO (97).
--
-- La torre es texto, igual que torre_nombre en RAC/ATS/Inspección: project_torre se reemplaza
-- entero cada vez que se edita en Configuración → Proyectos, así que no admite una FK.
--
-- Módulo «Propietarios» con la funcionalidad propietarios.gestion (la pantalla del mismo nombre).
-- Acceso inicial: ADMINISTRADOR DEL SISTEMA (1). Los demás roles se asignan desde Seguridad → Roles.
--
-- Requiere 20260929_ConvivirRolPropietario.sql (la pantalla asigna el rol 97).
-- Idempotente. Correr ANTES del deploy del backend.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS propietario (
    propietario_id     integer      GENERATED BY DEFAULT AS IDENTITY,
    person_id          integer      NOT NULL,
    project_id         integer      NOT NULL,
    torre              varchar(50),
    departamento       varchar(20)  NOT NULL,
    created_date_time  timestamptz  NOT NULL DEFAULT now(),
    created_user_id    integer      NOT NULL,
    updated_date_time  timestamptz,
    updated_user_id    integer,
    active             boolean      NOT NULL DEFAULT true,
    state              boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_propietario PRIMARY KEY (propietario_id),
    CONSTRAINT fk_propietario_person  FOREIGN KEY (person_id)  REFERENCES person (person_id),
    CONSTRAINT fk_propietario_project FOREIGN KEY (project_id) REFERENCES project (project_id)
);

COMMENT ON TABLE propietario IS
    'Inmuebles de los propietarios de la app Convivir Abril: una fila por persona y departamento.';
COMMENT ON COLUMN propietario.torre IS
    'Texto sin la palabra «Torre» (A, 1). Null en un edificio de una sola torre.';

-- La misma persona no puede tener dos veces el mismo departamento vigente. Dos dueños del mismo
-- departamento sí (son dos personas). El backend guarda torre y departamento en mayúsculas.
CREATE UNIQUE INDEX IF NOT EXISTS uq_propietario_inmueble
    ON propietario (person_id, project_id, coalesce(torre, ''), departamento)
    WHERE state;

CREATE INDEX IF NOT EXISTS ix_propietario_person_id  ON propietario (person_id)  WHERE state;
CREATE INDEX IF NOT EXISTS ix_propietario_project_id ON propietario (project_id) WHERE state;

-- ── Módulo y funcionalidad ─────────────────────────────────────────────────
INSERT INTO module (module_name)
SELECT 'Propietarios'
WHERE NOT EXISTS (SELECT 1 FROM module WHERE module_name = 'Propietarios');

INSERT INTO feature (feature_key, module_id)
SELECT 'propietarios.gestion', m.module_id
FROM module m
WHERE m.module_name = 'Propietarios'
ORDER BY m.module_id
LIMIT 1
ON CONFLICT (feature_key) DO NOTHING;

INSERT INTO role_feature (role_id, feature_id)
SELECT 1, f.feature_id
FROM feature f
WHERE f.feature_key = 'propietarios.gestion'
ON CONFLICT DO NOTHING;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM feature f JOIN role_feature rf ON rf.feature_id = f.feature_id
                   WHERE f.feature_key = 'propietarios.gestion' AND rf.role_id = 1) THEN
        RAISE EXCEPTION 'No quedó creada la funcionalidad propietarios.gestion para el rol 1. Abortado.';
    END IF;
END $$;

COMMIT;

-- Verificación
SELECT m.module_name, f.feature_key, string_agg(r.role_description, ', ') AS roles,
       to_regclass('public.propietario') IS NOT NULL AS tabla_creada
FROM feature f
JOIN module m            ON m.module_id  = f.module_id
LEFT JOIN role_feature rf ON rf.feature_id = f.feature_id
LEFT JOIN role r          ON r.role_id    = rf.role_id
WHERE f.feature_key = 'propietarios.gestion'
GROUP BY m.module_name, f.feature_key;
