-- ============================================================================
-- Notificaciones de los propietarios: la campana de la app Convivir Abril (RF-05)
-- ============================================================================
-- La campana de Inicio junta los avisos del propietario y cada uno lleva a su contenido: un hito
-- cumplido a Mi Proyecto, un documento nuevo a Mis documentos (RF-05 y sección 11 del documento
-- funcional). Los otros tipos de la sección 11 (comunicado, evento, encuesta, postventa) se suman
-- con sus módulos: una fila en propietario_notificacion_tipo y una columna que apunte a su
-- contenido (y el CHECK ck_propietario_notificacion_un_contenido, que la incluya).
--
-- El destinatario es la persona: la campana es de la cuenta y junta todas sus propiedades.
--   · HITO: un owner_milestone culminado (con fecha real) en la versión vigente del Cronograma de
--     Hitos de un proyecto donde tiene propiedades. Uno por persona, proyecto y hito, aunque tenga
--     dos departamentos en el mismo proyecto. Solo los culminados desde el día en que tiene su
--     primera propiedad en ese proyecto: lo anterior ya lo ve en Inicio como avance.
--   · DOCUMENTO: un documento que la intranet subió a una de sus propiedades.
--
-- Las filas las crea el backend al abrir la app (Inicio y la campana): el Cronograma de Hitos no
-- avisa cuando se culmina un hito, así que la app lo detecta. leida_date_time = cuando el
-- propietario la abrió desde la campana, o cuando abrió el documento.
--
-- Sin funcionalidad nueva en la intranet. Requiere 20260929_Propietarios.sql y
-- 20260930_PropietarioDocumentos.sql. Idempotente. Correr ANTES del deploy del backend: Inicio y
-- la descarga de documentos usan la tabla y sin ella dan error.
-- ============================================================================

BEGIN;

-- ── Tipos de aviso ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS propietario_notificacion_tipo (
    propietario_notificacion_tipo_id  integer      GENERATED BY DEFAULT AS IDENTITY,
    codigo                            varchar(30)  NOT NULL,
    nombre                            varchar(80)  NOT NULL,
    created_date_time                 timestamptz  NOT NULL DEFAULT now(),
    updated_date_time                 timestamptz,
    active                            boolean      NOT NULL DEFAULT true,
    state                             boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_propietario_notificacion_tipo PRIMARY KEY (propietario_notificacion_tipo_id)
);

COMMENT ON TABLE propietario_notificacion_tipo IS
    'Tipos de aviso de la campana de la app Convivir Abril. El backend los busca por codigo.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_propietario_notificacion_tipo_codigo
    ON propietario_notificacion_tipo (codigo)
    WHERE state;

INSERT INTO propietario_notificacion_tipo (codigo, nombre)
SELECT v.codigo, v.nombre
FROM (VALUES ('HITO', 'Avance de obra'),
             ('DOCUMENTO', 'Documento nuevo')) AS v (codigo, nombre)
WHERE NOT EXISTS (SELECT 1 FROM propietario_notificacion_tipo t
                  WHERE t.codigo = v.codigo AND t.state);

-- ── Avisos ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS propietario_notificacion (
    propietario_notificacion_id       integer      GENERATED BY DEFAULT AS IDENTITY,
    person_id                         integer      NOT NULL,
    propietario_notificacion_tipo_id  integer      NOT NULL,
    project_id                        integer,
    owner_milestone_id                integer,
    propietario_documento_id          integer,
    leida_date_time                   timestamptz,
    created_date_time                 timestamptz  NOT NULL DEFAULT now(),
    updated_date_time                 timestamptz,
    state                             boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_propietario_notificacion PRIMARY KEY (propietario_notificacion_id),
    CONSTRAINT fk_propietario_notificacion_person
        FOREIGN KEY (person_id) REFERENCES person (person_id),
    CONSTRAINT fk_propietario_notificacion_tipo
        FOREIGN KEY (propietario_notificacion_tipo_id)
        REFERENCES propietario_notificacion_tipo (propietario_notificacion_tipo_id),
    CONSTRAINT fk_propietario_notificacion_project
        FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_propietario_notificacion_owner_milestone
        FOREIGN KEY (owner_milestone_id) REFERENCES owner_milestone (owner_milestone_id),
    CONSTRAINT fk_propietario_notificacion_documento
        FOREIGN KEY (propietario_documento_id) REFERENCES propietario_documento (propietario_documento_id),
    -- Cada aviso apunta a UN contenido; el de hito, además, a su proyecto (el mismo
    -- owner_milestone es de todos los proyectos).
    CONSTRAINT ck_propietario_notificacion_un_contenido
        CHECK (num_nonnulls(owner_milestone_id, propietario_documento_id) = 1),
    CONSTRAINT ck_propietario_notificacion_hito_proyecto
        CHECK ((owner_milestone_id IS NULL) = (project_id IS NULL))
);

COMMENT ON TABLE propietario_notificacion IS
    'Avisos de la campana de la app Convivir Abril: uno por persona y contenido. Los crea el backend al abrir la app.';
COMMENT ON COLUMN propietario_notificacion.person_id IS
    'Destinatario: el propietario. La campana es de la cuenta y junta todas sus propiedades.';
COMMENT ON COLUMN propietario_notificacion.project_id IS
    'Solo HITO: el proyecto del hito.';
COMMENT ON COLUMN propietario_notificacion.leida_date_time IS
    'Cuando el propietario la abrió desde la campana (o abrió el documento). Null = la campana la cuenta como nueva.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_propietario_notificacion_hito
    ON propietario_notificacion (person_id, project_id, owner_milestone_id)
    WHERE state AND owner_milestone_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_propietario_notificacion_documento
    ON propietario_notificacion (propietario_documento_id)
    WHERE state AND propietario_documento_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_propietario_notificacion_person_id
    ON propietario_notificacion (person_id)
    WHERE state;

COMMIT;

-- Verificación
SELECT (SELECT string_agg(codigo, ', ' ORDER BY propietario_notificacion_tipo_id)
        FROM propietario_notificacion_tipo WHERE state)            AS tipos,
       to_regclass('public.propietario_notificacion') IS NOT NULL  AS tabla_notificaciones;
