-- ============================================================================
-- Documentos de los propietarios (app Convivir Abril)
-- ============================================================================
-- La intranet (Propietarios → Documentos) sube la minuta, los contratos, los comprobantes y los
-- manuales de cada propietario, y la app los muestra en «Mis documentos» (RF-09 del documento
-- funcional). Mientras no haya integración con SPERANT, la carga es manual.
--
-- Cada documento es de UNA propiedad del propietario (fila de propietario = persona + departamento):
-- el que tiene dos departamentos ve en cada uno lo suyo, y dos dueños del mismo departamento tienen
-- cada uno sus documentos. Los archivos van a SharePoint, a la carpeta registrada en
-- propietario_documento_folder (una sola vigente); cada documento guarda dónde quedó (drive_id +
-- item_id), así que cambiar la carpeta no mueve los que ya se subieron.
--
-- leido_date_time = la primera vez que el propietario lo abrió en la app. Hasta entonces la app lo
-- marca «Nuevo».
--
-- Sin funcionalidad nueva: se gestionan desde la pantalla Propietarios (propietarios.gestion).
-- Requiere 20260929_Propietarios.sql. Idempotente. Correr ANTES del deploy del backend: el Inicio
-- de la app cuenta los documentos nuevos y sin la tabla da error.
-- ============================================================================

BEGIN;

-- ── Tipos de documento ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS propietario_documento_tipo (
    propietario_documento_tipo_id  integer      GENERATED BY DEFAULT AS IDENTITY,
    nombre                         varchar(80)  NOT NULL,
    orden                          integer      NOT NULL DEFAULT 0,
    created_date_time              timestamptz  NOT NULL DEFAULT now(),
    updated_date_time              timestamptz,
    active                         boolean      NOT NULL DEFAULT true,
    state                          boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_propietario_documento_tipo PRIMARY KEY (propietario_documento_tipo_id)
);

COMMENT ON TABLE propietario_documento_tipo IS
    'Tipos de documento del propietario (minuta, contrato, comprobante...). La app filtra por tipo.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_propietario_documento_tipo_nombre
    ON propietario_documento_tipo (lower(nombre))
    WHERE state;

INSERT INTO propietario_documento_tipo (nombre, orden)
SELECT v.nombre, v.orden
FROM (VALUES ('Minuta', 1),
             ('Contrato', 2),
             ('Comprobante de pago', 3),
             ('Manual del propietario', 4),
             ('Reglamento interno', 5),
             ('Garantía', 6),
             ('Planos', 7),
             ('Otro', 99)) AS v (nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM propietario_documento_tipo t
                  WHERE lower(t.nombre) = lower(v.nombre) AND t.state);

-- ── Carpeta de SharePoint (una sola vigente) ───────────────────────────────
CREATE TABLE IF NOT EXISTS propietario_documento_folder (
    propietario_documento_folder_id  integer       GENERATED BY DEFAULT AS IDENTITY,
    link_url                         text          NOT NULL,
    folder_name                      varchar(200),
    created_date_time                timestamptz   NOT NULL DEFAULT now(),
    created_user_id                  integer,
    updated_date_time                timestamptz,
    updated_user_id                  integer,
    active                           boolean       NOT NULL DEFAULT true,
    state                            boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_propietario_documento_folder PRIMARY KEY (propietario_documento_folder_id)
);

COMMENT ON TABLE propietario_documento_folder IS
    'Carpeta de SharePoint donde se suben los documentos de los propietarios. Dentro se crea una carpeta por proyecto y, en ella, una por propiedad.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_propietario_documento_folder_vigente
    ON propietario_documento_folder ((true))
    WHERE state AND active;

-- ── Documentos ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS propietario_documento (
    propietario_documento_id       integer       GENERATED BY DEFAULT AS IDENTITY,
    propietario_id                 integer       NOT NULL,
    propietario_documento_tipo_id  integer       NOT NULL,
    nombre                         varchar(150)  NOT NULL,
    archivo_nombre                 varchar(255)  NOT NULL,
    archivo_content_type           varchar(100)  NOT NULL,
    archivo_tamano_bytes           bigint        NOT NULL,
    archivo_url                    text          NOT NULL,
    archivo_drive_id               varchar(200)  NOT NULL,
    archivo_item_id                varchar(200)  NOT NULL,
    leido_date_time                timestamptz,
    created_date_time              timestamptz   NOT NULL DEFAULT now(),
    created_user_id                integer       NOT NULL,
    updated_date_time              timestamptz,
    updated_user_id                integer,
    active                         boolean       NOT NULL DEFAULT true,
    state                          boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_propietario_documento PRIMARY KEY (propietario_documento_id),
    CONSTRAINT fk_propietario_documento_propietario
        FOREIGN KEY (propietario_id) REFERENCES propietario (propietario_id),
    CONSTRAINT fk_propietario_documento_tipo
        FOREIGN KEY (propietario_documento_tipo_id)
        REFERENCES propietario_documento_tipo (propietario_documento_tipo_id)
);

COMMENT ON TABLE propietario_documento IS
    'Documentos de una propiedad del propietario (minuta, contratos, comprobantes, manuales) que ve en la app Convivir Abril.';
COMMENT ON COLUMN propietario_documento.archivo_nombre IS
    'Nombre del archivo que se subió (con extensión), para descargarlo con ese nombre.';
COMMENT ON COLUMN propietario_documento.leido_date_time IS
    'Primera vez que el propietario lo abrió en la app. Null = la app lo muestra como nuevo.';

CREATE INDEX IF NOT EXISTS ix_propietario_documento_propietario_id
    ON propietario_documento (propietario_id)
    WHERE state;

COMMIT;

-- ── Carpeta: la registra el script de cada ambiente ────────────────────────
-- Después de este: 20260930_PropietarioDocumentoFolder_Prod.sql en prod y
-- 20260930_PropietarioDocumentoFolder_DevDemo.sql en dev y demo. Sin fila vigente, subir un
-- documento avisa que falta.

-- Verificación
SELECT (SELECT string_agg(nombre, ', ' ORDER BY orden)
        FROM propietario_documento_tipo WHERE state)              AS tipos,
       to_regclass('public.propietario_documento') IS NOT NULL    AS tabla_documentos,
       (SELECT link_url FROM propietario_documento_folder
        WHERE state AND active)                                   AS carpeta;
