-- Migración manual (pgAdmin) — CursoModule: cursos de capacitación interactivos
-- tipo Genially (ej. prevención de caídas) con evaluación auditable para SUNAFIL.
-- 5 tablas: curso, curso_slide, curso_intento, curso_intento_respuesta,
-- curso_intento_evidencia (auditoría legal 1:1 con curso_intento).

BEGIN;

CREATE TABLE IF NOT EXISTS curso (
    id                       integer GENERATED BY DEFAULT AS IDENTITY,
    titulo                   varchar(200)  NOT NULL,
    descripcion              text          NULL,
    categoria_nombre         varchar(150)  NULL,
    rol_destino              varchar(50)   NULL,
    nota_minima_aprobacion   numeric(5,2)  NOT NULL,
    activo                   boolean       NOT NULL DEFAULT true,
    created_at               timestamptz   NOT NULL DEFAULT now(),
    updated_at               timestamptz   NULL,
    CONSTRAINT pk_curso PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS curso_slide (
    id                  integer GENERATED BY DEFAULT AS IDENTITY,
    curso_id            integer       NOT NULL,
    orden               integer       NOT NULL,
    tipo_codigo         varchar(50)   NOT NULL,
    es_evaluable        boolean       NOT NULL DEFAULT false,
    puntaje             numeric(5,2)  NULL,
    modo_correccion     varchar(30)   NULL,
    configuracion_json  jsonb         NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    updated_at          timestamptz   NULL,
    CONSTRAINT pk_curso_slide PRIMARY KEY (id),
    CONSTRAINT fk_curso_slide_curso FOREIGN KEY (curso_id) REFERENCES curso (id)
);

CREATE TABLE IF NOT EXISTS curso_intento (
    id           integer GENERATED BY DEFAULT AS IDENTITY,
    curso_id     integer       NOT NULL,
    user_id      integer       NOT NULL,
    fecha_inicio timestamptz   NOT NULL,
    fecha_fin    timestamptz   NULL,
    nota_final   numeric(5,2)  NULL,
    aprobado     boolean       NULL,
    estado       varchar(20)   NOT NULL DEFAULT 'en_progreso',
    CONSTRAINT pk_curso_intento PRIMARY KEY (id),
    CONSTRAINT fk_curso_intento_curso FOREIGN KEY (curso_id) REFERENCES curso (id)
);

CREATE TABLE IF NOT EXISTS curso_intento_respuesta (
    id                     integer GENERATED BY DEFAULT AS IDENTITY,
    curso_intento_id       integer       NOT NULL,
    curso_slide_id         integer       NOT NULL,
    respuesta_json         jsonb         NOT NULL DEFAULT '{}'::jsonb,
    es_correcta            boolean       NULL,
    puntaje_obtenido       numeric(5,2)  NULL,
    tiempo_respuesta_seg   integer       NULL,
    created_at             timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT pk_curso_intento_respuesta PRIMARY KEY (id),
    CONSTRAINT fk_curso_intento_respuesta_intento FOREIGN KEY (curso_intento_id) REFERENCES curso_intento (id),
    CONSTRAINT fk_curso_intento_respuesta_slide FOREIGN KEY (curso_slide_id) REFERENCES curso_slide (id)
);

-- Auditoría legal (SUNAFIL): 1:1 con curso_intento, nunca se borra ni se simplifica.
CREATE TABLE IF NOT EXISTS curso_intento_evidencia (
    id                          integer GENERATED BY DEFAULT AS IDENTITY,
    curso_intento_id            integer       NOT NULL,
    ip_address                  varchar(64)   NOT NULL,
    latitud                     numeric(9,6)  NULL,
    longitud                    numeric(9,6)  NULL,
    precision_gps_metros        numeric(9,2)  NULL,
    user_agent                  text          NOT NULL,
    device_fingerprint          varchar(200)  NULL,
    declaracion_jurada_aceptada boolean       NOT NULL DEFAULT false,
    declaracion_texto           text          NOT NULL DEFAULT '',
    hash_sha256                 varchar(64)   NULL,
    created_at                  timestamptz   NOT NULL DEFAULT now(),
    sellado_at                  timestamptz   NULL,
    CONSTRAINT pk_curso_intento_evidencia PRIMARY KEY (id),
    CONSTRAINT fk_curso_intento_evidencia_intento FOREIGN KEY (curso_intento_id) REFERENCES curso_intento (id),
    CONSTRAINT uq_curso_intento_evidencia_intento UNIQUE (curso_intento_id)
);

CREATE INDEX IF NOT EXISTS ix_curso_slide_curso_orden ON curso_slide (curso_id, orden);
CREATE INDEX IF NOT EXISTS ix_curso_intento_curso_user ON curso_intento (curso_id, user_id);
CREATE INDEX IF NOT EXISTS ix_curso_intento_respuesta_intento ON curso_intento_respuesta (curso_intento_id);
CREATE INDEX IF NOT EXISTS ix_curso_intento_respuesta_slide ON curso_intento_respuesta (curso_slide_id);

COMMIT;
