-- ============================================================================
-- Cronograma de Hitos: configuración de correos y recordatorios
-- ============================================================================
-- El Cronograma de Hitos manda tres correos que hasta hoy tenían los destinatarios escritos en el
-- código. Desde Cronograma de Hitos → Configuración cada uno se prende y se apaga, y cada
-- destinatario también:
--   · VERSION_CON_CAMBIOS (Correos): cuando un residente sube una versión que cambia hitos o
--     fechas. Hoy: calvarez@abril.pe y alvarezvillegaschristian@outlook.com.
--   · CRONOGRAMA_PENDIENTE (Recordatorios): los últimos días hábiles del mes, al residente que
--     todavía no subió la versión del mes. Hoy: el residente, jefesgerenciadeproyectos@ y coriundo@
--     (Para), hmamani@ y vcolonio@ (CC) y calvarez@ (CCO).
--   · RESUMEN_MENSUAL (Recordatorios): el primer día del mes, las versiones que se subieron el mes
--     anterior. Hoy: calvarez@abril.pe y alvarezvillegaschristian@outlook.com.
-- Este script carga esos mismos destinatarios: al desplegar nadie deja de recibir ni empieza a
-- recibir nada. (El resumen, además, pasa a traer el mes que cerró: hasta ahora buscaba el mes que
-- empezaba y casi nunca salía.)
--
-- Tablas: la sección (Correos / Recordatorios), el tipo de destinatario (trabajador, rol o correo
-- escrito a mano), cómo lo recibe (Para, CC o CCO), el correo y sus destinatarios. El destinatario
-- que pone el sistema en cada envío (el residente, en el recordatorio) no es una fila: es
-- principal_nombre + principal_active del correo.
--
-- Funcionalidad nueva: mejora-continua.milestone-schedule.configuracion, para ADMINISTRADOR DEL
-- SISTEMA (rol 1). Hay que volver a iniciar sesión para ver el botón «Configuración».
--
-- Requiere la feature mejora-continua.milestone-schedule. Idempotente. Correr ANTES del deploy del
-- backend: sin las tablas, esos tres correos no salen y la pantalla de configuración da error.
-- ============================================================================

BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM feature WHERE feature_key = 'mejora-continua.milestone-schedule') THEN
        RAISE EXCEPTION 'No existe la feature mejora-continua.milestone-schedule. Abortado.';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM role WHERE role_id = 1 AND state) THEN
        RAISE EXCEPTION 'No existe el rol 1 (ADMINISTRADOR DEL SISTEMA). Abortado.';
    END IF;
END $$;

-- ── Secciones de la pantalla ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS milestone_schedule_correo_grupo (
    milestone_schedule_correo_grupo_id  integer      GENERATED BY DEFAULT AS IDENTITY,
    codigo                              varchar(30)  NOT NULL,
    nombre                              varchar(80)  NOT NULL,
    orden                               integer      NOT NULL DEFAULT 0,
    created_date_time                   timestamptz  NOT NULL DEFAULT now(),
    updated_date_time                   timestamptz,
    active                              boolean      NOT NULL DEFAULT true,
    state                               boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_milestone_schedule_correo_grupo PRIMARY KEY (milestone_schedule_correo_grupo_id)
);

COMMENT ON TABLE milestone_schedule_correo_grupo IS
    'Secciones de Cronograma de Hitos → Configuración: los correos que dispara una acción y los recordatorios que dispara el calendario.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_schedule_correo_grupo_codigo
    ON milestone_schedule_correo_grupo (codigo)
    WHERE state;

INSERT INTO milestone_schedule_correo_grupo (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES ('CORREOS', 'Correos', 1),
             ('RECORDATORIOS', 'Recordatorios', 2)) AS v (codigo, nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM milestone_schedule_correo_grupo g
                  WHERE g.codigo = v.codigo AND g.state);

-- ── Tipos de destinatario ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS milestone_schedule_correo_destinatario_tipo (
    milestone_schedule_correo_destinatario_tipo_id  integer      GENERATED BY DEFAULT AS IDENTITY,
    codigo                                          varchar(30)  NOT NULL,
    nombre                                          varchar(80)  NOT NULL,
    orden                                           integer      NOT NULL DEFAULT 0,
    created_date_time                               timestamptz  NOT NULL DEFAULT now(),
    updated_date_time                               timestamptz,
    active                                          boolean      NOT NULL DEFAULT true,
    state                                           boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_milestone_schedule_correo_destinatario_tipo PRIMARY KEY (milestone_schedule_correo_destinatario_tipo_id)
);

COMMENT ON TABLE milestone_schedule_correo_destinatario_tipo IS
    'A quién apunta un destinatario: un trabajador, un rol (le llega a quien lo tenga ese día) o un correo escrito a mano.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_schedule_correo_destinatario_tipo_codigo
    ON milestone_schedule_correo_destinatario_tipo (codigo)
    WHERE state;

INSERT INTO milestone_schedule_correo_destinatario_tipo (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES ('TRABAJADOR', 'Trabajador', 1),
             ('ROL', 'Rol', 2),
             ('CORREO', 'Correo escrito a mano', 3)) AS v (codigo, nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM milestone_schedule_correo_destinatario_tipo t
                  WHERE t.codigo = v.codigo AND t.state);

-- ── Cómo recibe el correo ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS milestone_schedule_correo_recepcion (
    milestone_schedule_correo_recepcion_id  integer      GENERATED BY DEFAULT AS IDENTITY,
    codigo                                  varchar(30)  NOT NULL,
    nombre                                  varchar(80)  NOT NULL,
    orden                                   integer      NOT NULL DEFAULT 0,
    created_date_time                       timestamptz  NOT NULL DEFAULT now(),
    updated_date_time                       timestamptz,
    active                                  boolean      NOT NULL DEFAULT true,
    state                                   boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_milestone_schedule_correo_recepcion PRIMARY KEY (milestone_schedule_correo_recepcion_id)
);

COMMENT ON TABLE milestone_schedule_correo_recepcion IS
    'Cómo recibe el correo un destinatario: Para, CC o CCO (copia oculta).';

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_schedule_correo_recepcion_codigo
    ON milestone_schedule_correo_recepcion (codigo)
    WHERE state;

INSERT INTO milestone_schedule_correo_recepcion (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES ('PARA', 'Para', 1),
             ('CC', 'CC', 2),
             ('CCO', 'CCO', 3)) AS v (codigo, nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM milestone_schedule_correo_recepcion r
                  WHERE r.codigo = v.codigo AND r.state);

-- ── Correos ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS milestone_schedule_correo (
    milestone_schedule_correo_id        integer       GENERATED BY DEFAULT AS IDENTITY,
    milestone_schedule_correo_grupo_id  integer       NOT NULL,
    codigo                              varchar(40)   NOT NULL,
    nombre                              varchar(80)   NOT NULL,
    descripcion                         varchar(300),
    orden                               integer       NOT NULL DEFAULT 0,
    principal_nombre                    varchar(120),
    principal_active                    boolean       NOT NULL DEFAULT true,
    created_date_time                   timestamptz   NOT NULL DEFAULT now(),
    updated_date_time                   timestamptz,
    updated_user_id                     integer,
    active                              boolean       NOT NULL DEFAULT true,
    state                               boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_milestone_schedule_correo PRIMARY KEY (milestone_schedule_correo_id),
    CONSTRAINT fk_milestone_schedule_correo_grupo
        FOREIGN KEY (milestone_schedule_correo_grupo_id)
        REFERENCES milestone_schedule_correo_grupo (milestone_schedule_correo_grupo_id)
);

COMMENT ON TABLE milestone_schedule_correo IS
    'Correos y recordatorios del Cronograma de Hitos. El backend los busca por codigo.';
COMMENT ON COLUMN milestone_schedule_correo.active IS
    'Interruptor del correo: false = no se envía a nadie (sus destinatarios se conservan).';
COMMENT ON COLUMN milestone_schedule_correo.principal_nombre IS
    'El destinatario que pone el sistema en cada envío (p. ej. el residente). Null = el correo no tiene.';
COMMENT ON COLUMN milestone_schedule_correo.principal_active IS
    'false = no le llega al destinatario del sistema, solo a la lista de destinatarios.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_schedule_correo_codigo
    ON milestone_schedule_correo (codigo)
    WHERE state;

INSERT INTO milestone_schedule_correo
    (milestone_schedule_correo_grupo_id, codigo, nombre, descripcion, orden, principal_nombre)
SELECT g.milestone_schedule_correo_grupo_id, v.codigo, v.nombre, v.descripcion, v.orden, v.principal
FROM (VALUES
        ('CORREOS', 'VERSION_CON_CAMBIOS', 'Versión con cambios',
         'Cuando un residente sube una versión que cambia hitos o fechas. Lleva lo que cambió.', 1, NULL),
        ('RECORDATORIOS', 'CRONOGRAMA_PENDIENTE', 'Cronograma pendiente',
         'Los últimos días hábiles del mes, al residente que todavía no subió la versión del mes.', 1,
         'El residente de la obra'),
        ('RECORDATORIOS', 'RESUMEN_MENSUAL', 'Resumen del mes',
         'El primer día del mes, con las versiones que se subieron el mes anterior.', 2, NULL)
     ) AS v (grupo, codigo, nombre, descripcion, orden, principal)
JOIN milestone_schedule_correo_grupo g ON g.codigo = v.grupo AND g.state
WHERE NOT EXISTS (SELECT 1 FROM milestone_schedule_correo c
                  WHERE c.codigo = v.codigo AND c.state);

-- ── Destinatarios de cada correo ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS milestone_schedule_correo_destinatario (
    milestone_schedule_correo_destinatario_id       integer       GENERATED BY DEFAULT AS IDENTITY,
    milestone_schedule_correo_id                    integer       NOT NULL,
    milestone_schedule_correo_destinatario_tipo_id  integer       NOT NULL,
    milestone_schedule_correo_recepcion_id          integer       NOT NULL,
    worker_id                                       integer,
    role_id                                         integer,
    correo                                          varchar(200),
    orden                                           integer       NOT NULL DEFAULT 0,
    created_date_time                               timestamptz   NOT NULL DEFAULT now(),
    created_user_id                                 integer       NOT NULL,
    updated_date_time                               timestamptz,
    updated_user_id                                 integer,
    active                                          boolean       NOT NULL DEFAULT true,
    state                                           boolean       NOT NULL DEFAULT true,
    CONSTRAINT pk_milestone_schedule_correo_destinatario PRIMARY KEY (milestone_schedule_correo_destinatario_id),
    CONSTRAINT fk_milestone_schedule_correo_destinatario_correo
        FOREIGN KEY (milestone_schedule_correo_id)
        REFERENCES milestone_schedule_correo (milestone_schedule_correo_id),
    CONSTRAINT fk_milestone_schedule_correo_destinatario_tipo
        FOREIGN KEY (milestone_schedule_correo_destinatario_tipo_id)
        REFERENCES milestone_schedule_correo_destinatario_tipo (milestone_schedule_correo_destinatario_tipo_id),
    CONSTRAINT fk_milestone_schedule_correo_destinatario_recepcion
        FOREIGN KEY (milestone_schedule_correo_recepcion_id)
        REFERENCES milestone_schedule_correo_recepcion (milestone_schedule_correo_recepcion_id),
    CONSTRAINT fk_milestone_schedule_correo_destinatario_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id),
    CONSTRAINT fk_milestone_schedule_correo_destinatario_role
        FOREIGN KEY (role_id) REFERENCES role (role_id),
    -- Apunta a una sola cosa: el trabajador, el rol o el correo escrito a mano.
    CONSTRAINT ck_milestone_schedule_correo_destinatario_uno
        CHECK (num_nonnulls(worker_id, role_id, correo) = 1)
);

COMMENT ON TABLE milestone_schedule_correo_destinatario IS
    'Destinatarios de un correo del Cronograma de Hitos. active = el interruptor de la fila; state = false, eliminado.';

-- El mismo destinatario entra una sola vez a cada correo (con Para, CC o CCO, no con los tres).
CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_schedule_correo_destinatario_worker
    ON milestone_schedule_correo_destinatario (milestone_schedule_correo_id, worker_id)
    WHERE state AND worker_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_schedule_correo_destinatario_role
    ON milestone_schedule_correo_destinatario (milestone_schedule_correo_id, role_id)
    WHERE state AND role_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_schedule_correo_destinatario_correo
    ON milestone_schedule_correo_destinatario (milestone_schedule_correo_id, lower(correo))
    WHERE state AND correo IS NOT NULL;

-- Los que hoy están escritos en el código. Una persona con ficha entra como trabajador (se ve su
-- nombre); el buzón de grupo y el correo personal, como correo escrito a mano. Solo si el correo
-- todavía no tiene ningún destinatario: correrlo de nuevo no revive los que se quitaron.
WITH v (correo_codigo, email, recepcion, orden) AS (
    VALUES ('VERSION_CON_CAMBIOS',  'calvarez@abril.pe',                    'PARA', 1),
           ('VERSION_CON_CAMBIOS',  'alvarezvillegaschristian@outlook.com', 'PARA', 2),
           ('CRONOGRAMA_PENDIENTE', 'jefesgerenciadeproyectos@abril.pe',    'PARA', 1),
           ('CRONOGRAMA_PENDIENTE', 'coriundo@abril.pe',                    'PARA', 2),
           ('CRONOGRAMA_PENDIENTE', 'hmamani@abril.pe',                     'CC',   3),
           ('CRONOGRAMA_PENDIENTE', 'vcolonio@abril.pe',                    'CC',   4),
           ('CRONOGRAMA_PENDIENTE', 'calvarez@abril.pe',                    'CCO',  5),
           ('RESUMEN_MENSUAL',      'calvarez@abril.pe',                    'PARA', 1),
           ('RESUMEN_MENSUAL',      'alvarezvillegaschristian@outlook.com', 'PARA', 2)
),
x AS (
    SELECT c.milestone_schedule_correo_id           AS correo_id,
           r.milestone_schedule_correo_recepcion_id AS recepcion_id,
           v.email,
           v.orden,
           (SELECT w.id
            FROM workers w
            WHERE lower(w.email_corporativo) = v.email AND w.state
            ORDER BY w.id DESC
            LIMIT 1) AS worker_id
    FROM v
    JOIN milestone_schedule_correo c           ON c.codigo = v.correo_codigo AND c.state
    JOIN milestone_schedule_correo_recepcion r ON r.codigo = v.recepcion AND r.state
)
INSERT INTO milestone_schedule_correo_destinatario
    (milestone_schedule_correo_id, milestone_schedule_correo_destinatario_tipo_id,
     milestone_schedule_correo_recepcion_id, worker_id, correo, orden, created_user_id)
SELECT x.correo_id,
       t.milestone_schedule_correo_destinatario_tipo_id,
       x.recepcion_id,
       x.worker_id,
       CASE WHEN x.worker_id IS NULL THEN x.email END,
       x.orden,
       1
FROM x
JOIN milestone_schedule_correo_destinatario_tipo t
     ON t.codigo = CASE WHEN x.worker_id IS NULL THEN 'CORREO' ELSE 'TRABAJADOR' END AND t.state
WHERE NOT EXISTS (SELECT 1 FROM milestone_schedule_correo_destinatario d
                  WHERE d.milestone_schedule_correo_id = x.correo_id AND d.state);

-- ── Funcionalidad: la pantalla de configuración ────────────────────────────
INSERT INTO feature (feature_key, module_id)
SELECT 'mejora-continua.milestone-schedule.configuracion', ver.module_id
FROM feature ver
WHERE ver.feature_key = 'mejora-continua.milestone-schedule'
ON CONFLICT (feature_key) DO NOTHING;

INSERT INTO role_feature (role_id, feature_id)
SELECT 1, f.feature_id
FROM feature f
WHERE f.feature_key = 'mejora-continua.milestone-schedule.configuracion'
ON CONFLICT (role_id, feature_id) DO NOTHING;

COMMIT;

-- Verificación: cada correo con sus destinatarios (Para / CC / CCO) y quién tiene la funcionalidad.
SELECT c.codigo,
       c.active,
       c.principal_nombre,
       string_agg(r.codigo || ' ' || coalesce(p.full_name, d.correo), ' · ' ORDER BY r.orden, d.orden) AS destinatarios
FROM milestone_schedule_correo c
LEFT JOIN milestone_schedule_correo_destinatario d ON d.milestone_schedule_correo_id = c.milestone_schedule_correo_id AND d.state
LEFT JOIN milestone_schedule_correo_recepcion r    ON r.milestone_schedule_correo_recepcion_id = d.milestone_schedule_correo_recepcion_id
LEFT JOIN workers w                                ON w.id = d.worker_id
LEFT JOIN person p                                 ON p.person_id = w.person_id
WHERE c.state
GROUP BY c.codigo, c.active, c.principal_nombre, c.orden, c.milestone_schedule_correo_grupo_id
ORDER BY c.milestone_schedule_correo_grupo_id, c.orden;
