-- ============================================================================
-- Costos y Presupuestos · Configuración — Sección "Pasos"
-- Fecha: 2026-08-31
--
-- Sección nueva en /costs/configuration: agrupa, paso por paso del flujo de
-- adjudicaciones, las opciones que se pueden prender/apagar sin tocar código.
--
-- Modelo: cada fila de project_sub_contractor_step_option ES una opción. La
-- descripción es la etiqueta del checkbox y `enabled` es su valor, así que
-- agregar una opción más adelante es un INSERT (dato), no una columna nueva ni
-- un deploy del frontend: la pantalla agrupa por paso y renderiza lo que haya.
-- El paso es FK a project_sub_contractor_status (los mismos 9 pasos del flujo),
-- no un número suelto.
--
-- Primera opción — Paso 4: "Permitir volver a generar el contrato completo".
-- Apagada por defecto. Prendida, deja regenerar el paquete PDF desde el paso 4
-- aunque la adjudicación ya haya avanzado; NO reabre el envío del correo al SC
-- (el botón sigue siendo "Siguiente paso").
--
-- Idempotente: IF NOT EXISTS + inserts guardados por NOT EXISTS.
-- Aplicar en dev y en producción.
-- ============================================================================

-- 1) Tabla de opciones por paso ----------------------------------------------
CREATE TABLE IF NOT EXISTS project_sub_contractor_step_option (
    project_sub_contractor_step_option_id integer GENERATED BY DEFAULT AS IDENTITY,
    project_sub_contractor_status_id      integer      NOT NULL,
    option_key                            varchar(100) NOT NULL,
    option_description                    varchar(200) NOT NULL,
    enabled                               boolean      NOT NULL DEFAULT false,
    display_order                         integer      NOT NULL DEFAULT 1,
    created_date_time                     timestamptz  NOT NULL DEFAULT now(),
    created_user_id                       integer      NULL,
    updated_date_time                     timestamptz  NULL,
    updated_user_id                       integer      NULL,
    active                                boolean      NOT NULL DEFAULT true,
    state                                 boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_project_sub_contractor_step_option
        PRIMARY KEY (project_sub_contractor_step_option_id),
    CONSTRAINT fk_project_sub_contractor_step_option_status
        FOREIGN KEY (project_sub_contractor_status_id)
        REFERENCES project_sub_contractor_status (project_sub_contractor_status_id)
);

-- Una sola opción vigente por clave (el soft delete deja convivir las dadas de baja).
CREATE UNIQUE INDEX IF NOT EXISTS ux_psc_step_option_key_vigente
    ON project_sub_contractor_step_option (option_key)
    WHERE state = true;

-- Índice de lectura de la pantalla: opciones vigentes agrupadas por paso.
CREATE INDEX IF NOT EXISTS ix_psc_step_option_status
    ON project_sub_contractor_step_option (project_sub_contractor_status_id, display_order)
    WHERE state = true;

-- 2) Opción del Paso 4 --------------------------------------------------------
-- El paso se referencia por descripción del estado, no por el id 4 a pelo.
INSERT INTO project_sub_contractor_step_option
       (project_sub_contractor_status_id, option_key, option_description, enabled, display_order)
SELECT s.project_sub_contractor_status_id,
       'paso4.permitir-regenerar-paquete',
       'Permitir volver a generar el contrato completo',
       false,
       1
FROM project_sub_contractor_status s
WHERE s.project_sub_contractor_status_description = 'Por enviar al SC'
  AND NOT EXISTS (
      SELECT 1 FROM project_sub_contractor_step_option
       WHERE option_key = 'paso4.permitir-regenerar-paquete' AND state = true
  );

-- 3) Feature de la sección ----------------------------------------------------
INSERT INTO feature (feature_key, module_id)
SELECT 'costs.config.pasos', f.module_id
FROM feature f
WHERE f.feature_key = 'costs.config.adjudicacion-folder'
  AND NOT EXISTS (SELECT 1 FROM feature WHERE feature_key = 'costs.config.pasos');

-- 4) Acceso: los mismos 3 roles que ya ven el resto de la configuración de
--    adjudicaciones (6 Of. Central, 7 Administrador C. y Ppto., 61 Of. Técnica).
INSERT INTO role_feature (role_id, feature_id)
SELECT r.role_id, f.feature_id
FROM feature f
CROSS JOIN (VALUES (6), (7), (61)) AS r(role_id)
WHERE f.feature_key = 'costs.config.pasos'
  AND NOT EXISTS (
      SELECT 1 FROM role_feature rf WHERE rf.role_id = r.role_id AND rf.feature_id = f.feature_id
  );
