-- ============================================================================
-- Centro de aprendizaje — videos subidos como archivo a SharePoint.
-- Fecha: 2026-09-16
--
-- Hasta ahora un video solo podía ser un enlace (Loom, Stream, etc.). Ahora también se
-- puede subir el archivo desde Configuración → Centro de aprendizaje: va a la carpeta de
-- SharePoint registrada en learning_video_folder y el video guarda en url el link del
-- reproductor de Stream (el mismo formato de los que se pegaban a mano), más el
-- drive_id / item_id del archivo.
--
--   1) learning_video_folder: carpeta destino (singleton), mismo patrón que
--      gth_carta_oferta_folder. Se cambia sin redeploy con el UPDATE del final.
--   2) learning_video: file_name / drive_id / item_id. NULL = el video es un enlace.
--   3) learning_video.url pasa a varchar(1000): el link de Stream lleva la ruta del
--      archivo codificada y con tildes o nombres largos supera los 500.
--
-- ORDEN: correr ANTES de desplegar el backend. El modelo de EF ya mapea las columnas
-- nuevas y sin ellas la pantalla de administración falla (42703). El backend actual no
-- se ve afectado por correrlo antes: todo es aditivo.
--
-- Idempotente. Va igual en dev y en producción (dev también sube a la biblioteca real,
-- como las cartas oferta).
-- ============================================================================

BEGIN;

-- 1) Carpeta destino (singleton) ----------------------------------------------
CREATE TABLE IF NOT EXISTS learning_video_folder (
    learning_video_folder_id integer GENERATED BY DEFAULT AS IDENTITY,
    link_url          text        NOT NULL,
    folder_name       text        NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_learning_video_folder PRIMARY KEY (learning_video_folder_id)
);

-- A lo sumo una fila vigente.
CREATE UNIQUE INDEX IF NOT EXISTS ux_learning_video_folder_singleton
    ON learning_video_folder ((true)) WHERE state = true;

INSERT INTO learning_video_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/Manuales%20y%20videos/Forms/AllItems.aspx',
    'Manuales y videos'
WHERE NOT EXISTS (SELECT 1 FROM learning_video_folder WHERE state = true);

-- 2) Archivo del video --------------------------------------------------------
ALTER TABLE learning_video ADD COLUMN IF NOT EXISTS file_name varchar(255);
ALTER TABLE learning_video ADD COLUMN IF NOT EXISTS drive_id  varchar(500);
ALTER TABLE learning_video ADD COLUMN IF NOT EXISTS item_id   varchar(500);

-- Los tres van juntos: o el video es un archivo (los tres) o es un enlace (ninguno).
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_learning_video_archivo') THEN
        ALTER TABLE learning_video
            ADD CONSTRAINT ck_learning_video_archivo
            CHECK ((file_name IS NULL) = (item_id IS NULL) AND (drive_id IS NULL) = (item_id IS NULL));
    END IF;
END $$;

-- 3) url más larga -------------------------------------------------------------
ALTER TABLE learning_video ALTER COLUMN url TYPE varchar(1000);

COMMIT;

-- 4) Cómo cambiar la carpeta más adelante (NO se ejecuta ahora) ------------------
-- Pegar el link de la nueva carpeta/biblioteca de SharePoint. Los videos ya subidos
-- siguen abriéndose desde donde están; solo cambian los nuevos.
--
-- UPDATE learning_video_folder
--    SET link_url          = '<nuevo link de SharePoint>',
--        folder_name       = '<nombre legible, solo referencia>',
--        updated_date_time = now()
--  WHERE state = true;
