-- ============================================================================
-- Gestión GTH · Reclutamiento — Condiciones de contrato de la carta oferta
-- Fecha: 2026-09-01
--
-- La plantilla nueva de la carta oferta saca el bloque de condiciones de contrato
-- del documento (antes iba escrito a mano dentro del Word, igual para todos) y lo
-- vuelve el marcador {{CONDICIONES}}: ahora GTH escribe N condiciones por carta y
-- cada una sale como una viñeta.
--
-- Van en tabla hija y no en una columna de texto con saltos de línea porque son N
-- ítems por carta, con orden propio, que se vuelven a mostrar en el formulario al
-- regenerar el documento.
--
-- Idempotente: CREATE TABLE / CREATE INDEX IF NOT EXISTS y la FK guardada por
-- NOT EXISTS. Seguro de correr tal cual en dev, demo y producción.
--
-- NO hay nada que rellenar para las cartas anteriores: las que ya se generaron
-- llevan el bloque de condiciones impreso dentro de su .docx (venía en la plantilla
-- vieja), así que quedan correctas con cero filas acá. Solo las cartas nuevas usan
-- esta tabla.
-- ============================================================================

BEGIN;

-- 1) Tabla ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_carta_oferta_condicion (
    gth_carta_oferta_condicion_id integer GENERATED BY DEFAULT AS IDENTITY,
    gth_carta_oferta_id           integer     NOT NULL,
    -- Posición de la viñeta dentro del bloque, empezando en 1.
    orden                         integer     NOT NULL,
    texto                         text        NOT NULL,
    created_date_time             timestamptz NOT NULL DEFAULT now(),
    created_user_id               integer     NULL,
    updated_date_time             timestamptz NULL,
    updated_user_id               integer     NULL,
    active                        boolean     NOT NULL DEFAULT true,
    state                         boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_carta_oferta_condicion PRIMARY KEY (gth_carta_oferta_condicion_id)
);

-- 2) FK a la carta oferta ---------------------------------------------------
-- Con guarda porque ADD CONSTRAINT no admite IF NOT EXISTS y este script se
-- puede re-correr.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_gth_carta_oferta_condicion_carta'
    ) THEN
        ALTER TABLE gth_carta_oferta_condicion
            ADD CONSTRAINT fk_gth_carta_oferta_condicion_carta
            FOREIGN KEY (gth_carta_oferta_id)
            REFERENCES gth_carta_oferta (gth_carta_oferta_id);
    END IF;
END $$;

-- 3) Índice de lectura ------------------------------------------------------
-- Se leen siempre por carta y en orden, que es exactamente como se imprimen.
CREATE INDEX IF NOT EXISTS ix_gth_carta_oferta_condicion_carta_orden
    ON gth_carta_oferta_condicion (gth_carta_oferta_id, orden);

COMMIT;
