-- ============================================================================
-- Gestión Administrativa — Varias firmas sobre el MISMO consolidado.
--
-- Qué cambia y por qué
--
-- El consolidado ya sabía acumular firmas: se estampan una al costado de la
-- otra (SignaturePdfStamper, parámetro `slot`) y cada una se aplica sobre la
-- copia ya firmada. Pero QUIÉN firmó se deducía de `ga_rendicion.firmado_por_id`,
-- que es UNO por planilla, porque ese mecanismo se hizo para un consolidado que
-- mezclaba dos jefaturas: cada una firmaba por sus propias planillas.
--
-- Desde el 2026-09-21 hacen falta DOS firmas sobre las MISMAS planillas: en obra
-- firman el administrador de obra y después el residente. Eso ya no entra en una
-- columna por planilla, así que las firmas pasan a ser filas.
--
-- El documento no queda firmado —ni pagable por Tesorería— hasta que estén todas
-- las que su área exige (area_revisores_rendicion.aprueba_consolidado, o el
-- algoritmo: administrador + residente).
--
-- ORDEN DE EJECUCIÓN
--   • ANTES de desplegar. El backend nuevo lee esta tabla al resolver qué firmas
--     faltan; sin ella responde 42P01 y se cae Consolidados.
--   • El INSERT de abajo migra las firmas que ya existen para que los
--     consolidados a medio firmar no pierdan lo andado ni se firmen dos veces.
--
-- Re-ejecutable: IF NOT EXISTS + WHERE NOT EXISTS.
-- ============================================================================

SET client_encoding TO 'UTF8';

BEGIN;

CREATE TABLE IF NOT EXISTS ga_consolidado_s10_firma (
    ga_consolidado_s10_firma_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consolidado_s10_id          integer NOT NULL REFERENCES ga_consolidado_s10(id),
    -- Quién firmó, por las dos vías: el usuario que apretó el botón y su ficha, que es con la que
    -- se compara contra los aprobadores que el area/algoritmo exige.
    firmado_por_id              integer NOT NULL REFERENCES app_user(user_id),
    worker_id                   integer          REFERENCES workers(id),
    -- Lugar de la firma en la hoja: 0 la primera, 1 la de al lado, etc. Es el `slot` con el que se
    -- estampo, guardado para que una refirma no tenga que recalcularlo y pise a otra.
    slot                        integer NOT NULL DEFAULT 0,
    firmado_at                  timestamptz NOT NULL DEFAULT now(),
    state                       boolean NOT NULL DEFAULT true,
    created_at                  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ga_consolidado_s10_firma_doc
    ON ga_consolidado_s10_firma (consolidado_s10_id) WHERE state;

-- Nadie firma dos veces el mismo documento.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_consolidado_s10_firma_vivo
    ON ga_consolidado_s10_firma (consolidado_s10_id, firmado_por_id) WHERE state;

COMMENT ON TABLE ga_consolidado_s10_firma IS
    'Firmas estampadas sobre un Consolidado del S10. Reemplaza a deducirlas de '
    'ga_rendicion.firmado_por_id, que solo admitia una por planilla: desde 2026-09-21 en obra '
    'firman el administrador de obra y el residente sobre las mismas planillas.';

-- ── Migración de lo ya firmado ──────────────────────────────────────────────
-- Cada (consolidado, firmante) que hoy se deduce de las planillas pasa a ser una fila. El slot se
-- reconstruye por orden de firma, que es el mismo criterio con el que se estamparon.
INSERT INTO ga_consolidado_s10_firma (consolidado_s10_id, firmado_por_id, worker_id, slot, firmado_at)
SELECT x.consolidado_s10_id,
       x.firmado_por_id,
       (SELECT w.id
        FROM   workers w
        JOIN   person p ON p.person_id = w.person_id
        WHERE  p.user_id = x.firmado_por_id AND w.state
        ORDER  BY w.id
        LIMIT  1),
       row_number() OVER (PARTITION BY x.consolidado_s10_id ORDER BY x.firmado_at, x.firmado_por_id) - 1,
       x.firmado_at
FROM (
    SELECT DISTINCT ON (v.consolidado_s10_id, r.firmado_por_id)
           v.consolidado_s10_id,
           r.firmado_por_id,
           r.firmado_at
    FROM   ga_consolidado_s10_rendicion v
    JOIN   ga_rendicion r ON r.id = v.rendicion_id
    WHERE  v.state
      AND  r.firmado_por_id IS NOT NULL
      AND  r.pdf_firmado_url IS NOT NULL
    ORDER  BY v.consolidado_s10_id, r.firmado_por_id, r.firmado_at
) x
WHERE NOT EXISTS (
    SELECT 1 FROM ga_consolidado_s10_firma f
    WHERE f.consolidado_s10_id = x.consolidado_s10_id
      AND f.firmado_por_id = x.firmado_por_id
      AND f.state
);

COMMIT;

-- ── Verificación (solo lectura) ─────────────────────────────────────────────
SELECT count(*) AS firmas_migradas,
       count(DISTINCT consolidado_s10_id) AS consolidados_con_firma,
       count(*) FILTER (WHERE worker_id IS NULL) AS sin_ficha_resuelta
FROM   ga_consolidado_s10_firma
WHERE  state;
