-- ============================================================================
-- Gestión Administrativa — Revisores de Áreas propios de Rendiciones.
--
-- Qué cambia y por qué
--
-- Hasta hoy `area_revisores` definía TRES cosas a la vez: quién aprueba la
-- salida, quién aprueba la primera revisión de la planilla y quién firma el
-- consolidado. Entra el ADMINISTRADOR DE OBRA al flujo (project.workers_coord_admin_id,
-- el campo que la pantalla de Proyectos llamaba "Coordinador administrativo") y
-- esos papeles se separan:
--
--   • `area_revisores`            -> SOLO aprobar la salida. No cambia nada suyo.
--   • `area_revisores_rendicion`  -> primera revisión + firma del consolidado.
--
-- La tabla nueva es igual a `area_revisores` más dos banderas, porque acá un
-- área filtrada por proyecto tiene varios aprobadores a la vez y no todos
-- intervienen en los dos pasos:
--
--   • aprueba_primera_revision -> su visto bueno hace falta en la 1.ª revisión;
--   • aprueba_consolidado      -> su firma hace falta en el consolidado.
--
-- Con más de una fila marcada, TODAS tienen que aprobar. El caso que motivó
-- esto: en obra aprueba la primera revisión solo el administrador de obra, y el
-- consolidado lo firman el administrador de obra y el residente, en ese orden.
--
-- ORDEN DE EJECUCIÓN
--   • ANTES de desplegar. El backend nuevo lee esta tabla al resolver la primera
--     revisión y el firmante del consolidado; sin ella responde 42P01.
--   • Arranca VACÍA a propósito: sin filas, el algoritmo resuelve solo (el
--     administrador de obra de la obra, o la jefatura del área) igual que hace
--     hoy `area_revisores` cuando un área no tiene nada cargado. No hay que
--     migrar nada desde `area_revisores`: son papeles distintos y copiarlos
--     dejaría a los aprobadores de salidas firmando consolidados sin que nadie
--     lo haya pedido.
--
-- Re-ejecutable: IF NOT EXISTS en todo.
-- ============================================================================

SET client_encoding TO 'UTF8';

BEGIN;

CREATE TABLE IF NOT EXISTS area_revisores_rendicion (
    area_revisores_rendicion_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_scope_id               integer NOT NULL REFERENCES area_scope(area_scope_id),
    project_id                  integer          REFERENCES project(project_id),
    revisor_id                  integer NOT NULL REFERENCES workers(id),
    orden_prioridad             integer NOT NULL DEFAULT 1,
    aprueba_primera_revision    boolean NOT NULL DEFAULT true,
    aprueba_consolidado         boolean NOT NULL DEFAULT true,
    active                      boolean NOT NULL DEFAULT true,
    state                       boolean NOT NULL DEFAULT true,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz,
    CONSTRAINT chk_area_revisores_rendicion_prioridad CHECK (orden_prioridad >= 1)
);

CREATE INDEX IF NOT EXISTS ix_area_revisores_rendicion_area
    ON area_revisores_rendicion (area_scope_id) WHERE state;

CREATE INDEX IF NOT EXISTS ix_area_revisores_rendicion_proyecto
    ON area_revisores_rendicion (area_scope_id, project_id) WHERE state;

-- Mismo criterio que area_revisores: un revisor por (área, proyecto) mientras esté vivo,
-- y NULLS NOT DISTINCT para que el nivel de área (project_id NULL) tampoco se duplique.
CREATE UNIQUE INDEX IF NOT EXISTS ux_area_revisores_rendicion_vivo
    ON area_revisores_rendicion (area_scope_id, project_id, revisor_id)
    NULLS NOT DISTINCT WHERE state;

COMMENT ON TABLE area_revisores_rendicion IS
    'Aprobadores de la primera revision de la planilla y firmantes del Consolidado del S10, por area '
    '(y por proyecto si el area filtra). Separada de area_revisores, que quedo solo para aprobar la salida.';

COMMENT ON COLUMN area_revisores_rendicion.aprueba_primera_revision IS
    'Su visto bueno hace falta en la primera revision. Con varias filas marcadas, todas tienen que aprobar.';

COMMENT ON COLUMN area_revisores_rendicion.aprueba_consolidado IS
    'Su firma hace falta en el Consolidado del S10 y su planilla grupal. Con varias filas marcadas, '
    'todas tienen que firmar, en orden de orden_prioridad.';

COMMIT;

-- ── Verificación (solo lectura) ─────────────────────────────────────────────
SELECT count(*) AS filas_cargadas FROM area_revisores_rendicion;
