-- ============================================================================
-- Gestión Administrativa — los correos del flujo pasan a agruparse por la
-- pantalla donde se originan, y el plazo para rendir deja de estar hardcodeado.
--
-- 1) ga_correo_pantalla (catálogo nuevo): la pantalla desde la que se dispara
--    cada correo. Reemplaza a la pantalla única Configuración → Correos, que se
--    dio de baja: ahora cada pantalla del flujo tiene su propio botón
--    «Configuración» y administra solo sus correos.
--
-- 2) ga_correo_evento.pantalla_id: a qué pantalla pertenece cada correo.
--    El criterio es DÓNDE SE ORIGINA el correo, no a quién le llega:
--      • Solicitud de Salidas  → los dos que salen al crear la solicitud.
--      • Gestión de Salidas    → la decisión del revisor sobre la solicitud.
--      • Mis Rendiciones       → los que dispara el trabajador (enviar la
--                                planilla a 1.ª revisión y avisar del S10).
--      • Gestión de Rendiciones→ las dos decisiones del revisor (1.ª revisión
--                                y reembolso).
--      • Reembolsos            → hoy ninguno: Tesorería solo marca pagado y eso
--                                no envía correos. La pantalla queda registrada
--                                para cuando exista uno.
--
-- 3) ga_rendicion_config (tabla nueva, singleton): los días hábiles de plazo
--    para rendir un mes, contados sobre el mes siguiente. Antes era la
--    constante CalendarioNoLaborable.DiasHabilesDePlazo = 7; se configura desde
--    Mis Rendiciones → Configuración → Días reembolsables y arranca en 5, que
--    es el plazo pedido por GTH.
--
-- ORDEN DE EJECUCIÓN
--   • Correr ANTES de desplegar el backend: el código nuevo lee
--     ga_rendicion_config y ga_correo_evento.pantalla_id en cada listado de
--     salidas, así que desplegar primero deja esas pantallas en 500. Al
--     revés no hay problema: el backend viejo no escribe ga_correo_evento.
--   • Correr DESPUÉS de 20260904_GaRendicionPrimeraRevision.sql, que agrega
--     los cuatro correos de la primera revisión. Si se corre al revés, ese
--     script fallaría con 23502 al insertarlos sin pantalla_id — de ahí la
--     guarda de abajo, que aborta con el nombre del script que falta.
--
-- Re-ejecutable: los IF NOT EXISTS / ON CONFLICT dejan cada sentencia sin
-- efecto si ya se corrió. Los ids salen de la secuencia, no se fijan a mano.
-- Correr TODO junto (no hay pasos "solo después del deploy").
-- ============================================================================

BEGIN;

-- ── 0) Prerrequisito: los cuatro correos de la primera revisión ─────────────
-- pantalla_id queda NOT NULL, así que todo correo tiene que existir ya. Si
-- faltan, se aborta acá y no a mitad del script siguiente.
DO $$
DECLARE faltantes text;
BEGIN
    SELECT string_agg(c.codigo, ', ') INTO faltantes
    FROM   (VALUES ('REN_PRIMERA_REVISION'), ('REN_ENVIADA'),
                   ('REN_PRIMERA_APROBADA'), ('REN_PRIMERA_OBSERVADA')) AS c(codigo)
    WHERE  NOT EXISTS (
        SELECT 1 FROM ga_correo_evento e WHERE e.codigo = c.codigo AND e.state
    );

    IF faltantes IS NOT NULL THEN
        RAISE EXCEPTION
            'Faltan correos en ga_correo_evento: %. Correr primero Migrations/Manual/20260904_GaRendicionPrimeraRevision.sql.',
            faltantes;
    END IF;
END $$;

-- ── 1) Catálogo de pantallas ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ga_correo_pantalla (
    id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     varchar(50)  NOT NULL,
    nombre     varchar(150) NOT NULL,
    orden      integer      NOT NULL DEFAULT 0,
    active     boolean      NOT NULL DEFAULT true,
    state      boolean      NOT NULL DEFAULT true,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz
);

COMMENT ON TABLE ga_correo_pantalla IS
    'Pantalla de Gestion Administrativa desde la que se origina cada correo del flujo de salidas. Es lo que agrupa ga_correo_evento en la Configuracion de cada pantalla.';

CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_correo_pantalla_codigo
    ON ga_correo_pantalla (lower(codigo)) WHERE state;

INSERT INTO ga_correo_pantalla (codigo, nombre, orden)
VALUES
    ('SOLICITUD_SALIDAS',   'Solicitud de Salidas',   1),
    ('RENDICIONES',         'Mis Rendiciones',        2),
    ('GESTION_SALIDAS',     'Gestion de Salidas',     3),
    ('GESTION_RENDICIONES', 'Gestion de Rendiciones', 4),
    ('REEMBOLSOS',          'Reembolsos',             5)
ON CONFLICT DO NOTHING;

-- ── 2) A qué pantalla pertenece cada correo ─────────────────────────────────
ALTER TABLE ga_correo_evento
    ADD COLUMN IF NOT EXISTS pantalla_id integer;

UPDATE ga_correo_evento e
SET    pantalla_id = p.id
FROM   ga_correo_pantalla p
WHERE  e.pantalla_id IS NULL
  AND  p.state
  AND  p.codigo = CASE e.codigo
        WHEN 'REVISOR'                  THEN 'SOLICITUD_SALIDAS'
        WHEN 'CONFIRMACION'             THEN 'SOLICITUD_SALIDAS'
        WHEN 'APROBADA'                 THEN 'GESTION_SALIDAS'
        WHEN 'RECHAZADA'                THEN 'GESTION_SALIDAS'
        WHEN 'REN_PRIMERA_REVISION'     THEN 'RENDICIONES'
        WHEN 'REN_ENVIADA'              THEN 'RENDICIONES'
        WHEN 'S10_REVISOR'              THEN 'RENDICIONES'
        WHEN 'REN_PRIMERA_APROBADA'     THEN 'GESTION_RENDICIONES'
        WHEN 'REN_PRIMERA_OBSERVADA'    THEN 'GESTION_RENDICIONES'
        WHEN 'REEMBOLSO_APROBADO'       THEN 'GESTION_RENDICIONES'
        WHEN 'REEMBOLSO_RECHAZADO'      THEN 'GESTION_RENDICIONES'
       END;

-- Guarda: si quedara algún correo sin pantalla, el NOT NULL de abajo lo cortaría
-- con un mensaje que no dice cuál. Se aborta con el código a la vista.
DO $$
DECLARE huerfanos text;
BEGIN
    SELECT string_agg(codigo, ', ') INTO huerfanos
    FROM   ga_correo_evento
    WHERE  state AND pantalla_id IS NULL;

    IF huerfanos IS NOT NULL THEN
        RAISE EXCEPTION 'Correos sin pantalla asignada: %. Agregarlos al CASE antes de seguir.', huerfanos;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE  conname = 'ga_correo_evento_pantalla_id_fkey'
    ) THEN
        ALTER TABLE ga_correo_evento
            ADD CONSTRAINT ga_correo_evento_pantalla_id_fkey
            FOREIGN KEY (pantalla_id) REFERENCES ga_correo_pantalla (id);
    END IF;
END $$;

ALTER TABLE ga_correo_evento
    ALTER COLUMN pantalla_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ga_correo_evento_pantalla
    ON ga_correo_evento (pantalla_id) WHERE state;

COMMENT ON COLUMN ga_correo_evento.pantalla_id IS
    'Pantalla donde se ORIGINA el correo (no a quien le llega): es la Configuracion en la que se administra.';

-- ── 3) Plazo para rendir, configurable ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS ga_rendicion_config (
    id                 integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dias_habiles_plazo integer     NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_user_id    integer,
    updated_at         timestamptz,
    updated_user_id    integer,
    state              boolean     NOT NULL DEFAULT true,
    CONSTRAINT ck_ga_rendicion_config_dias
        CHECK (dias_habiles_plazo BETWEEN 1 AND 28)
);

COMMENT ON TABLE ga_rendicion_config IS
    'Configuracion global de las rendiciones (fila unica). Hoy solo el plazo en dias habiles.';
COMMENT ON COLUMN ga_rendicion_config.dias_habiles_plazo IS
    'Dias habiles del mes SIGUIENTE que dura el plazo para rendir un mes. Antes era la constante CalendarioNoLaborable.DiasHabilesDePlazo.';

-- Fila única: la configuración es global, no por área ni por trabajador.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_rendicion_config_singleton
    ON ga_rendicion_config ((true)) WHERE state;

INSERT INTO ga_rendicion_config (dias_habiles_plazo)
SELECT 5
WHERE NOT EXISTS (SELECT 1 FROM ga_rendicion_config WHERE state);

COMMIT;

-- ============================================================================
-- Verificación
-- ============================================================================
-- SELECT p.codigo AS pantalla, e.orden, e.codigo, e.nombre
-- FROM   ga_correo_evento e
-- JOIN   ga_correo_pantalla p ON p.id = e.pantalla_id
-- WHERE  e.state
-- ORDER  BY p.orden, e.orden;
--
-- SELECT * FROM ga_rendicion_config WHERE state;
