START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702044852_AddSsProyectoHabilitado') THEN
    ALTER INDEX ix_ev_evaluacion_contratista_detalle_evaluacion_id RENAME TO ix_ev_evaluacion_contratista_detalle_evaluacion_contratista_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702044852_AddSsProyectoHabilitado') THEN
    CREATE TABLE ss_proyecto_habilitado (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        proyecto_id integer NOT NULL,
        active boolean NOT NULL,
        created_date_time timestamp with time zone NOT NULL,
        created_user_id integer NOT NULL,
        updated_date_time timestamp with time zone,
        updated_user_id integer,
        state boolean NOT NULL,
        CONSTRAINT pk_ss_proyecto_habilitado PRIMARY KEY (id),
        CONSTRAINT fk_ss_proyecto_habilitado_project_proyecto_id FOREIGN KEY (proyecto_id) REFERENCES project (project_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702044852_AddSsProyectoHabilitado') THEN
    CREATE INDEX ix_ss_proyecto_habilitado_proyecto_id ON ss_proyecto_habilitado (proyecto_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702044852_AddSsProyectoHabilitado') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260702044852_AddSsProyectoHabilitado', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702175538_AddObsRevisorToSsDossierDocumento') THEN
    ALTER INDEX ix_ev_evaluacion_contratista_detalle_evaluacion_id RENAME TO ix_ev_evaluacion_contratista_detalle_evaluacion_contratista_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702175538_AddObsRevisorToSsDossierDocumento') THEN
    ALTER TABLE ss_dossier_documento ADD obs_revisor text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702175538_AddObsRevisorToSsDossierDocumento') THEN
    CREATE TABLE ss_charla_contratista (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        proyecto_id integer NOT NULL,
        empresa_id integer NOT NULL,
        fecha date NOT NULL,
        tema character varying(200) NOT NULL,
        descripcion text,
        evidencia_url character varying(1000),
        evidencia_nombre character varying(300),
        subido_por_user_id integer,
        created_at timestamp with time zone NOT NULL,
        state boolean NOT NULL,
        CONSTRAINT pk_ss_charla_contratista PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260702175538_AddObsRevisorToSsDossierDocumento') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260702175538_AddObsRevisorToSsDossierDocumento', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704060000_AddFactorConversionYCantidadReal') THEN
    ALTER TABLE ss_material_alias ADD factor_conversion numeric NOT NULL DEFAULT 1.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704060000_AddFactorConversionYCantidadReal') THEN
    ALTER TABLE ss_consumo_linea ADD cantidad_real numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704060000_AddFactorConversionYCantidadReal') THEN
    ALTER TABLE ss_consumo_linea ADD precio_unitario_real numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704060000_AddFactorConversionYCantidadReal') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260704060000_AddFactorConversionYCantidadReal', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704070000_AddIncluidoManualRatioProyecto') THEN
    ALTER TABLE ss_ratio_proyecto ADD incluido_manual boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704070000_AddIncluidoManualRatioProyecto') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260704070000_AddIncluidoManualRatioProyecto', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704080000_SplitIncluidoManualRatioYPrecio') THEN
    ALTER TABLE ss_ratio_proyecto RENAME COLUMN incluido_manual TO incluido_manual_ratio;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704080000_SplitIncluidoManualRatioYPrecio') THEN
    ALTER TABLE ss_ratio_proyecto ADD incluido_manual_precio boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704080000_SplitIncluidoManualRatioYPrecio') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260704080000_SplitIncluidoManualRatioYPrecio', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704090000_RepointHitoAMilestoneSchedule') THEN
    ALTER TABLE ss_consumo_linea DROP CONSTRAINT fk_ss_consumo_linea_ss_material_hito_hito_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704090000_RepointHitoAMilestoneSchedule') THEN
    ALTER TABLE ss_presupuesto_personal_hito DROP CONSTRAINT fk_ss_presupuesto_personal_hito_ss_material_hito_hito_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704090000_RepointHitoAMilestoneSchedule') THEN
    ALTER TABLE ss_consumo_linea ADD CONSTRAINT fk_ss_consumo_linea_milestone_schedule_hito_id FOREIGN KEY (hito_id) REFERENCES milestone_schedule (milestone_schedule_id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704090000_RepointHitoAMilestoneSchedule') THEN
    ALTER TABLE ss_presupuesto_personal_hito ADD CONSTRAINT fk_ss_presupuesto_personal_hito_milestone_schedule_hito_id FOREIGN KEY (hito_id) REFERENCES milestone_schedule (milestone_schedule_id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704090000_RepointHitoAMilestoneSchedule') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260704090000_RepointHitoAMilestoneSchedule', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704100000_AddEsHitoCriticoToMilestoneSchedule') THEN
    ALTER TABLE milestone_schedule ADD es_hito_critico boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260704100000_AddEsHitoCriticoToMilestoneSchedule') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260704100000_AddEsHitoCriticoToMilestoneSchedule', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260705110000_AddCustomHitoToMilestoneSchedule') THEN
    ALTER TABLE milestone_schedule ALTER COLUMN milestone_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260705110000_AddCustomHitoToMilestoneSchedule') THEN
    ALTER TABLE milestone_schedule ADD custom_description text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260705110000_AddCustomHitoToMilestoneSchedule') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260705110000_AddCustomHitoToMilestoneSchedule', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260705162909_AddUserCronogramaPreference') THEN
    CREATE TABLE user_cronograma_preference (
        user_id integer NOT NULL,
        project_id integer NOT NULL,
        tipo_cronograma character varying(30) NOT NULL,
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT pk_user_cronograma_preference PRIMARY KEY (user_id, project_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260705162909_AddUserCronogramaPreference') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260705162909_AddUserCronogramaPreference', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260706090000_AddSsKitBom') THEN
    CREATE TABLE ss_kit (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre text NOT NULL,
        tipo_id integer NOT NULL,
        activo boolean NOT NULL,
        creado_en timestamp with time zone NOT NULL,
        CONSTRAINT pk_ss_kit PRIMARY KEY (id),
        CONSTRAINT fk_ss_kit_ss_material_tipo_tipo_id FOREIGN KEY (tipo_id) REFERENCES ss_material_tipo (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260706090000_AddSsKitBom') THEN
    CREATE TABLE ss_kit_item (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        kit_id integer NOT NULL,
        familia_id integer NOT NULL,
        cantidad_por_kit numeric NOT NULL,
        es_consumible boolean NOT NULL,
        CONSTRAINT pk_ss_kit_item PRIMARY KEY (id),
        CONSTRAINT fk_ss_kit_item_ss_kit_kit_id FOREIGN KEY (kit_id) REFERENCES ss_kit (id) ON DELETE CASCADE,
        CONSTRAINT fk_ss_kit_item_ss_material_familia_familia_id FOREIGN KEY (familia_id) REFERENCES ss_material_familia (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260706090000_AddSsKitBom') THEN
    CREATE INDEX ix_ss_kit_tipo_id ON ss_kit (tipo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260706090000_AddSsKitBom') THEN
    CREATE INDEX ix_ss_kit_item_kit_id ON ss_kit_item (kit_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260706090000_AddSsKitBom') THEN
    CREATE INDEX ix_ss_kit_item_familia_id ON ss_kit_item (familia_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260706090000_AddSsKitBom') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260706090000_AddSsKitBom', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    ALTER TABLE project ADD meta_ppc numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    ALTER TABLE project ADD responsable_planeamiento_bim text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    ALTER TABLE project ADD responsable_planeamiento_bim_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_macro_actividad (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre text NOT NULL,
        orden integer NOT NULL,
        CONSTRAINT pk_bim_macro_actividad PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_causa_no_cumplimiento (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre text NOT NULL,
        orden integer NOT NULL,
        CONSTRAINT pk_bim_causa_no_cumplimiento PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_fase (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre text NOT NULL,
        orden integer NOT NULL,
        CONSTRAINT pk_bim_fase PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_actividad (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        macro_actividad_id integer NOT NULL,
        nombre text NOT NULL,
        tipo text NOT NULL,
        orden integer NOT NULL,
        CONSTRAINT pk_bim_actividad PRIMARY KEY (id),
        CONSTRAINT fk_bim_actividad_bim_macro_actividad_macro_actividad_id FOREIGN KEY (macro_actividad_id) REFERENCES bim_macro_actividad (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_proyecto_zona (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        project_id integer NOT NULL,
        nombre text NOT NULL,
        orden integer NOT NULL,
        CONSTRAINT pk_bim_proyecto_zona PRIMARY KEY (id),
        CONSTRAINT fk_bim_proyecto_zona_project_project_id FOREIGN KEY (project_id) REFERENCES project (project_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_zona_nivel (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        zona_id integer NOT NULL,
        nombre text NOT NULL,
        orden integer NOT NULL,
        CONSTRAINT pk_bim_zona_nivel PRIMARY KEY (id),
        CONSTRAINT fk_bim_zona_nivel_bim_proyecto_zona_zona_id FOREIGN KEY (zona_id) REFERENCES bim_proyecto_zona (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_zona_sector (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        zona_id integer NOT NULL,
        nombre text NOT NULL,
        orden integer NOT NULL,
        CONSTRAINT pk_bim_zona_sector PRIMARY KEY (id),
        CONSTRAINT fk_bim_zona_sector_bim_proyecto_zona_zona_id FOREIGN KEY (zona_id) REFERENCES bim_proyecto_zona (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_proyecto_fase (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        project_id integer NOT NULL,
        fase_id integer NOT NULL,
        fecha_inicio date NOT NULL,
        fecha_fin_meta date NOT NULL,
        fecha_fin_real date,
        CONSTRAINT pk_bim_proyecto_fase PRIMARY KEY (id),
        CONSTRAINT fk_bim_proyecto_fase_bim_fase_fase_id FOREIGN KEY (fase_id) REFERENCES bim_fase (id) ON DELETE RESTRICT,
        CONSTRAINT fk_bim_proyecto_fase_project_project_id FOREIGN KEY (project_id) REFERENCES project (project_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_registro_diario (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        project_id integer NOT NULL,
        zona_id integer NOT NULL,
        nivel_id integer NOT NULL,
        sector_id integer NOT NULL,
        actividad_id integer NOT NULL,
        fecha date NOT NULL,
        cumplida boolean NOT NULL,
        causa_id integer,
        causa_detalle text,
        created_user_id integer NOT NULL,
        created_date_time timestamp with time zone NOT NULL,
        updated_user_id integer,
        updated_date_time timestamp with time zone,
        CONSTRAINT pk_bim_registro_diario PRIMARY KEY (id),
        CONSTRAINT fk_bim_registro_diario_bim_actividad_actividad_id FOREIGN KEY (actividad_id) REFERENCES bim_actividad (id) ON DELETE RESTRICT,
        CONSTRAINT fk_bim_registro_diario_bim_causa_no_cumplimiento_causa_id FOREIGN KEY (causa_id) REFERENCES bim_causa_no_cumplimiento (id) ON DELETE RESTRICT,
        CONSTRAINT fk_bim_registro_diario_bim_proyecto_zona_zona_id FOREIGN KEY (zona_id) REFERENCES bim_proyecto_zona (id) ON DELETE RESTRICT,
        CONSTRAINT fk_bim_registro_diario_bim_zona_nivel_nivel_id FOREIGN KEY (nivel_id) REFERENCES bim_zona_nivel (id) ON DELETE RESTRICT,
        CONSTRAINT fk_bim_registro_diario_bim_zona_sector_sector_id FOREIGN KEY (sector_id) REFERENCES bim_zona_sector (id) ON DELETE RESTRICT,
        CONSTRAINT fk_bim_registro_diario_project_project_id FOREIGN KEY (project_id) REFERENCES project (project_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_evidencia_foto (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        project_id integer NOT NULL,
        fecha date NOT NULL,
        url text NOT NULL,
        created_user_id integer NOT NULL,
        created_date_time timestamp with time zone NOT NULL,
        CONSTRAINT pk_bim_evidencia_foto PRIMARY KEY (id),
        CONSTRAINT fk_bim_evidencia_foto_project_project_id FOREIGN KEY (project_id) REFERENCES project (project_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE TABLE bim_bloqueo (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        project_id integer NOT NULL,
        descripcion text NOT NULL,
        estado text NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        fecha_actualizacion timestamp with time zone NOT NULL,
        fecha_cierre timestamp with time zone,
        created_user_id integer NOT NULL,
        CONSTRAINT pk_bim_bloqueo PRIMARY KEY (id),
        CONSTRAINT fk_bim_bloqueo_project_project_id FOREIGN KEY (project_id) REFERENCES project (project_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE UNIQUE INDEX ix_bim_actividad_macro_actividad_id_tipo_nombre ON bim_actividad (macro_actividad_id, tipo, nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_bloqueo_project_id ON bim_bloqueo (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE UNIQUE INDEX ix_bim_causa_no_cumplimiento_nombre ON bim_causa_no_cumplimiento (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_evidencia_foto_project_id_fecha ON bim_evidencia_foto (project_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE UNIQUE INDEX ix_bim_fase_nombre ON bim_fase (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE UNIQUE INDEX ix_bim_macro_actividad_nombre ON bim_macro_actividad (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_proyecto_fase_fase_id ON bim_proyecto_fase (fase_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_proyecto_fase_project_id ON bim_proyecto_fase (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_proyecto_zona_project_id ON bim_proyecto_zona (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_registro_diario_actividad_id ON bim_registro_diario (actividad_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_registro_diario_causa_id ON bim_registro_diario (causa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_registro_diario_nivel_id ON bim_registro_diario (nivel_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE UNIQUE INDEX ix_bim_registro_diario_project_id_zona_id_nivel_id_sector_id_a ON bim_registro_diario (project_id, zona_id, nivel_id, sector_id, actividad_id, fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_registro_diario_sector_id ON bim_registro_diario (sector_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_registro_diario_zona_id ON bim_registro_diario (zona_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_zona_nivel_zona_id ON bim_zona_nivel (zona_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    CREATE INDEX ix_bim_zona_sector_zona_id ON bim_zona_sector (zona_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    INSERT INTO bim_macro_actividad (nombre, orden) VALUES
        ('Estructura Sótanos', 1),
        ('Estructura Torre', 2),
        ('Losa contraterreno', 3)
    ON CONFLICT (nombre) DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    INSERT INTO bim_fase (nombre, orden) VALUES
        ('Diseño', 1),
        ('Movimiento de Tierras', 2),
        ('Casco', 3),
        ('Acabados', 4),
        ('Entrega', 5)
    ON CONFLICT (nombre) DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    INSERT INTO bim_causa_no_cumplimiento (nombre, orden) VALUES
        ('Falta de material', 1),
        ('Clima', 2),
        ('Mano de obra', 3),
        ('Diseño/Información pendiente', 4),
        ('Otro', 5)
    ON CONFLICT (nombre) DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    INSERT INTO bim_actividad (macro_actividad_id, nombre, tipo, orden)
    SELECT bim_macro_actividad.id, v.nombre, v.tipo, v.orden
    FROM bim_macro_actividad, (VALUES
        ('Acero de columnas y placas', 'VERTICAL', 1),
        ('Instalaciones (IIEE, IISS, IIGG)', 'VERTICAL', 2),
        ('Encofrado Columnas y Placas', 'VERTICAL', 3),
        ('Vaciado de concreto', 'VERTICAL', 4),
        ('Desencofrado/Resane/Curado', 'VERTICAL', 5),
        ('Colocación acero en vigas', 'HORIZONTAL', 6),
        ('Encofrado fondo de vigas', 'HORIZONTAL', 7),
        ('Encofrado laterales de vigas', 'HORIZONTAL', 8),
        ('Encofrado de losas', 'HORIZONTAL', 9),
        ('Colocación de prelosas', 'HORIZONTAL', 10),
        ('Instalaciones (IIEE, IISS, IIGG)', 'HORIZONTAL', 11),
        ('Colocación de acero en losas', 'HORIZONTAL', 12),
        ('Vaciado de concreto', 'HORIZONTAL', 13),
        ('Desencofrado', 'HORIZONTAL', 14)
    ) AS v(nombre, tipo, orden)
    WHERE bim_macro_actividad.nombre IN ('Estructura Sótanos', 'Estructura Torre')
    ON CONFLICT (macro_actividad_id, tipo, nombre) DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    INSERT INTO bim_actividad (macro_actividad_id, nombre, tipo, orden)
    SELECT bim_macro_actividad.id, v.nombre, v.tipo, v.orden
    FROM bim_macro_actividad, (VALUES
        ('Colocación acero en vigas', 'HORIZONTAL', 1),
        ('Encofrado fondo de vigas', 'HORIZONTAL', 2),
        ('Encofrado laterales de vigas', 'HORIZONTAL', 3),
        ('Encofrado de losas', 'HORIZONTAL', 4),
        ('Colocación de prelosas', 'HORIZONTAL', 5),
        ('Instalaciones (IIEE, IISS, IIGG)', 'HORIZONTAL', 6),
        ('Colocación de acero en losas', 'HORIZONTAL', 7),
        ('Vaciado de concreto', 'HORIZONTAL', 8),
        ('Desencofrado', 'HORIZONTAL', 9)
    ) AS v(nombre, tipo, orden)
    WHERE bim_macro_actividad.nombre = 'Losa contraterreno'
    ON CONFLICT (macro_actividad_id, tipo, nombre) DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260804221640_AddPlaneamientoBim') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260804221640_AddPlaneamientoBim', '10.0.2');
    END IF;
END $EF$;
COMMIT;

