-- =====================================================================================
-- Carta oferta: de primer paso de Onboarding a ÚLTIMO paso de Reclutamiento
-- =====================================================================================
-- Qué cambia:
--   • Nace `gth_carta_oferta`, dueña del expediente de la carta (envío, firma, aprobación
--     y file digital del colaborador). Antes esas columnas vivían en `gth_onboarding`.
--   • Reclutamiento gana dos fases al final: CARTA_OFERTA (esperando la firma del
--     candidato) y CARTA_OFERTA_FIRMADA (esperando la revisión de GTH). CERRADO deja de
--     ser la salida del EMO y pasa a ser la salida de aprobar la carta firmada.
--   • Onboarding pierde su fase CARTA_OFERTA_FIRMADA: su checklist arranca en FILE_DIGITAL
--     y todas las demás fases bajan un puesto.
--
-- Todo va en una transacción. El DROP de las columnas viejas de `gth_onboarding` NO está
-- acá: va en el bloque del final, que se corre SOLO DESPUÉS del deploy (el backend viejo
-- todavía las lee).
-- =====================================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────────────
-- 1. Tabla nueva: gth_carta_oferta
-- ─────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS gth_carta_oferta (
    gth_carta_oferta_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- A quién se le ofrece el puesto. La carta cuelga del candidato, no del requerimiento.
    gth_candidato_id             integer NOT NULL REFERENCES gth_candidato (gth_candidato_id),

    -- Ficha de la base maestra: ahí se guarda la firma que dibuja en el enlace público,
    -- así que sin ficha no se puede enviar la carta.
    person_id                    integer NOT NULL REFERENCES person (person_id),

    fecha_ingreso                date,

    -- Carta enviada (archivo en SharePoint + trazabilidad del envío)
    carta_nombre                 varchar(300),
    carta_url                    text,
    carta_item_id                varchar(200),
    carta_drive_id               varchar(200),
    correo                       varchar(200),
    enviada_date_time            timestamptz,
    enviada_user_id              integer,

    -- Credencial del enlace público donde el candidato lee y firma su carta.
    token                        varchar(100),

    -- Carta firmada (la que devuelve el candidato)
    firmada_nombre               varchar(300),
    firmada_url                  text,
    firmada_item_id              varchar(200),
    firmada_drive_id             varchar(200),
    firmada_subida_date_time     timestamptz,
    firmada_subida_user_id       integer,
    -- Con fecha, la firmó el candidato desde el enlace; en null con firmada_url llena, la
    -- subió GTH a mano (la vía de respaldo, para quien firma en papel).
    firmada_postulante_date_time timestamptz,

    -- Aprobación de GTH: es lo que cierra el requerimiento.
    aprobada_date_time           timestamptz,
    aprobada_user_id             integer,

    -- File digital del colaborador («{DNI} - {NOMBRE}» en la biblioteca configurada).
    file_digital_drive_id        varchar(200),
    file_digital_item_id         varchar(200),
    file_digital_ruta            text,

    created_date_time            timestamptz NOT NULL DEFAULT now(),
    created_user_id              integer,
    updated_date_time            timestamptz,
    updated_user_id              integer,
    active                       boolean NOT NULL DEFAULT true,
    state                        boolean NOT NULL DEFAULT true
);

-- Una sola carta viva por candidato.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_carta_oferta_candidato
    ON gth_carta_oferta (gth_candidato_id) WHERE state = true;

CREATE INDEX IF NOT EXISTS ix_gth_carta_oferta_person_id
    ON gth_carta_oferta (person_id);

-- El token es la única credencial de la página pública: no puede repetirse.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_carta_oferta_token
    ON gth_carta_oferta (token) WHERE state = true AND token IS NOT NULL;


-- ─────────────────────────────────────────────────────────────────────────────────────
-- 2. Migración de las cartas que hoy viven en gth_onboarding
-- ─────────────────────────────────────────────────────────────────────────────────────
-- Solo las que realmente tienen carta cargada. `person_id` es obligatorio en la tabla
-- nueva; los onboardings viejos que no lo tengan lo resuelven por el formulario del
-- postulante o por el fft_person_id del requerimiento, que es de donde salía.
INSERT INTO gth_carta_oferta (
    gth_candidato_id, person_id, fecha_ingreso,
    carta_nombre, carta_url, carta_item_id, carta_drive_id, correo,
    enviada_date_time, enviada_user_id, token,
    firmada_nombre, firmada_url, firmada_item_id, firmada_drive_id,
    firmada_subida_date_time, firmada_subida_user_id, firmada_postulante_date_time,
    aprobada_date_time, aprobada_user_id,
    file_digital_drive_id, file_digital_item_id, file_digital_ruta,
    created_date_time, created_user_id, updated_date_time, updated_user_id, active, state)
SELECT
    ob.gth_candidato_id,
    COALESCE(
        ob.person_id,
        (SELECT f.person_id FROM gth_postulante_formulario f
          WHERE f.gth_candidato_id = ob.gth_candidato_id AND f.state AND f.person_id IS NOT NULL
          ORDER BY f.gth_postulante_formulario_id DESC LIMIT 1),
        r.fft_person_id),
    ob.fecha_ingreso,
    ob.carta_oferta_nombre, ob.carta_oferta_url, ob.carta_oferta_item_id, ob.carta_oferta_drive_id,
    ob.carta_oferta_correo, ob.carta_oferta_enviada_date_time, ob.carta_oferta_enviada_user_id,
    ob.carta_oferta_token,
    ob.carta_firmada_nombre, ob.carta_firmada_url, ob.carta_firmada_item_id, ob.carta_firmada_drive_id,
    ob.carta_firmada_subida_date_time, ob.carta_firmada_subida_user_id, ob.carta_firmada_postulante_date_time,
    ob.carta_firmada_aprobada_date_time, ob.carta_firmada_aprobada_user_id,
    ob.file_digital_drive_id, ob.file_digital_item_id, ob.file_digital_ruta,
    ob.created_date_time, ob.created_user_id, ob.updated_date_time, ob.updated_user_id,
    ob.active, ob.state
FROM gth_onboarding ob
JOIN gth_candidato c   ON c.gth_candidato_id = ob.gth_candidato_id
JOIN gth_requerimiento r ON r.gth_requerimiento_id = c.gth_requerimiento_id
WHERE ob.state
  AND ob.carta_oferta_url IS NOT NULL
  AND COALESCE(
        ob.person_id,
        (SELECT f.person_id FROM gth_postulante_formulario f
          WHERE f.gth_candidato_id = ob.gth_candidato_id AND f.state AND f.person_id IS NOT NULL
          ORDER BY f.gth_postulante_formulario_id DESC LIMIT 1),
        r.fft_person_id) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM gth_carta_oferta x
                   WHERE x.gth_candidato_id = ob.gth_candidato_id AND x.state);

-- Aviso (no bloquea) si alguna carta se quedó sin migrar por no tener ficha en person:
-- esa carta seguiría abriéndose desde el file de SharePoint, pero no desde la pantalla.
DO $$
DECLARE v_huerfanas int;
BEGIN
    SELECT count(*) INTO v_huerfanas
    FROM gth_onboarding ob
    WHERE ob.state
      AND ob.carta_oferta_url IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM gth_carta_oferta x
                       WHERE x.gth_candidato_id = ob.gth_candidato_id AND x.state);
    IF v_huerfanas > 0 THEN
        RAISE NOTICE 'ATENCION: % carta(s) oferta no se migraron por no tener ficha en person.', v_huerfanas;
    END IF;
END $$;


-- ─────────────────────────────────────────────────────────────────────────────────────
-- 3. Fases del requerimiento: CARTA_OFERTA y CARTA_OFERTA_FIRMADA antes del cierre
-- ─────────────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM gth_estado_requerimiento WHERE codigo = 'CARTA_OFERTA' AND state) THEN
        RAISE NOTICE 'Las fases de carta oferta ya existen: se omite el bloque 3.';
        RETURN;
    END IF;

    -- El cierre (y el rechazado del GG, que va al final) corren un puesto para dejarle
    -- sitio a la carta oferta, que es el paso anterior.
    UPDATE gth_estado_requerimiento SET orden = orden + 1 WHERE orden >= 11;

    INSERT INTO gth_estado_requerimiento (codigo, nombre, orden, active, state, descripcion) VALUES
        ('CARTA_OFERTA', 'Carta oferta', 11, true, true,
         'GTH le envió la carta oferta al seleccionado; él la lee y la firma en línea desde el enlace que recibió por correo.'),
        -- active = false, igual que las fases de resultado del EMO: es un estado del
        -- requerimiento, no un paso propio de la línea de tiempo del seguimiento. Comparte
        -- el orden con CARTA_OFERTA, que es el paso vigente.
        ('CARTA_OFERTA_FIRMADA', 'Carta oferta firmada', 11, false, true,
         'El seleccionado ya firmó su carta oferta. GTH la revisa: al aprobarla, el proceso de reclutamiento queda cerrado.');

    -- CERRADO deja de ser la salida del EMO: ahora lo es de aprobar la carta firmada.
    UPDATE gth_estado_requerimiento
       SET descripcion = 'GTH aprobó la carta oferta firmada por el seleccionado: el proceso de reclutamiento termina y el colaborador pasa al proceso de onboarding.',
           updated_date_time = now()
     WHERE codigo = 'CERRADO' AND state;

    UPDATE gth_estado_requerimiento
       SET descripcion = 'El examen médico de ingreso del finalista salió Apto. Falta que GTH le envíe la carta oferta, que es el último paso del proceso.',
           updated_date_time = now()
     WHERE codigo = 'EMO_APTO' AND state;

    UPDATE gth_estado_requerimiento
       SET descripcion = 'El examen médico de ingreso del finalista salió Apto con Restricciones. Falta que GTH le envíe la carta oferta, que es el último paso del proceso.',
           updated_date_time = now()
     WHERE codigo = 'EMO_APTO_RESTRICCIONES' AND state;

    UPDATE gth_estado_requerimiento
       SET descripcion = 'GTH le programa el examen medico de ingreso al finalista aprobado antes de mandarle la carta oferta.',
           updated_date_time = now()
     WHERE codigo = 'EMO_INGRESO' AND state;
END $$;


-- ─────────────────────────────────────────────────────────────────────────────────────
-- 4. Onboarding: se va la fase de la carta oferta y el resto sube un puesto
-- ─────────────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
    v_fase_carta   int;
    v_fase_file    int;
    v_estado_proc  int;
BEGIN
    SELECT gth_onboarding_fase_id INTO v_fase_carta
      FROM gth_onboarding_fase WHERE codigo = 'CARTA_OFERTA_FIRMADA' AND state;

    IF v_fase_carta IS NULL THEN
        RAISE NOTICE 'La fase CARTA_OFERTA_FIRMADA del onboarding ya no existe: se omite el bloque 4.';
        RETURN;
    END IF;

    SELECT gth_onboarding_fase_id INTO v_fase_file
      FROM gth_onboarding_fase WHERE codigo = 'FILE_DIGITAL' AND state;
    IF v_fase_file IS NULL THEN
        RAISE EXCEPTION 'No existe la fase FILE_DIGITAL del onboarding: no hay a dónde mover lo de la carta oferta.';
    END IF;

    SELECT gth_onboarding_estado_id INTO v_estado_proc
      FROM gth_onboarding_estado WHERE codigo = 'EN_PROCESO' AND state;
    IF v_estado_proc IS NULL THEN
        RAISE EXCEPTION 'No existe el estado EN_PROCESO del onboarding.';
    END IF;

    -- 4.1 Los colaboradores parados en la fase que desaparece pasan a la primera fase nueva.
    UPDATE gth_onboarding
       SET gth_onboarding_fase_id = v_fase_file,
           updated_date_time      = now()
     WHERE state AND gth_onboarding_fase_id = v_fase_carta;

    -- 4.2 CARTA_ENVIADA ya no es un estado posible del onboarding: la carta se envía y se
    --     aprueba en Reclutamiento. Los que estaban ahí pasan a EN_PROCESO y el catálogo se
    --     desactiva (no se borra: hay historial que lo nombra).
    UPDATE gth_onboarding o
       SET gth_onboarding_estado_id = v_estado_proc,
           updated_date_time        = now()
      FROM gth_onboarding_estado e
     WHERE e.gth_onboarding_estado_id = o.gth_onboarding_estado_id
       AND e.codigo = 'CARTA_ENVIADA'
       AND o.state;

    UPDATE gth_onboarding_estado
       SET active = false, updated_date_time = now()
     WHERE codigo = 'CARTA_ENVIADA' AND state;

    -- 4.3 Las dos notificaciones preventivas (TI y responsable de obra) no eran de la carta
    --     oferta: se disparan al registrar la solicitud. Se mudan a la fase que pasa a ser
    --     la primera para no perderlas del checklist.
    UPDATE gth_onboarding_actividad
       SET gth_onboarding_fase_id = v_fase_file,
           orden                  = CASE codigo WHEN 'AVISO_TI' THEN 2 ELSE 3 END,
           updated_date_time      = now()
     WHERE codigo IN ('AVISO_TI', 'AVISO_OBRA') AND state;

    -- 4.4 Revisar y aprobar la carta firmada se hace ahora en Reclutamiento.
    UPDATE gth_onboarding_actividad
       SET state = false, active = false, updated_date_time = now()
     WHERE codigo = 'REVISAR_APROBAR_CARTA' AND state;

    -- 4.5 La fase de la carta oferta sale del checklist del onboarding y las demás suben.
    UPDATE gth_onboarding_fase
       SET state = false, active = false, updated_date_time = now()
     WHERE gth_onboarding_fase_id = v_fase_carta;

    UPDATE gth_onboarding_fase
       SET orden = orden - 1, updated_date_time = now()
     WHERE state AND orden > 1;
END $$;

COMMIT;


-- =====================================================================================
-- SOLO DESPUÉS DEL DEPLOY — no correr junto con lo de arriba
-- =====================================================================================
-- El backend anterior todavía lee estas columnas de gth_onboarding; el nuevo ya no las
-- toca (sus datos viven en gth_carta_oferta desde el bloque 2). Correr esto una vez que
-- la versión nueva esté arriba.
--
-- BEGIN;
-- DROP INDEX IF EXISTS ix_gth_onboarding_carta_oferta_token;
-- ALTER TABLE gth_onboarding
--     DROP COLUMN IF EXISTS carta_oferta_nombre,
--     DROP COLUMN IF EXISTS carta_oferta_url,
--     DROP COLUMN IF EXISTS carta_oferta_item_id,
--     DROP COLUMN IF EXISTS carta_oferta_drive_id,
--     DROP COLUMN IF EXISTS carta_oferta_correo,
--     DROP COLUMN IF EXISTS carta_oferta_enviada_date_time,
--     DROP COLUMN IF EXISTS carta_oferta_enviada_user_id,
--     DROP COLUMN IF EXISTS carta_oferta_token,
--     DROP COLUMN IF EXISTS carta_firmada_nombre,
--     DROP COLUMN IF EXISTS carta_firmada_url,
--     DROP COLUMN IF EXISTS carta_firmada_item_id,
--     DROP COLUMN IF EXISTS carta_firmada_drive_id,
--     DROP COLUMN IF EXISTS carta_firmada_subida_date_time,
--     DROP COLUMN IF EXISTS carta_firmada_subida_user_id,
--     DROP COLUMN IF EXISTS carta_firmada_postulante_date_time,
--     DROP COLUMN IF EXISTS carta_firmada_aprobada_date_time,
--     DROP COLUMN IF EXISTS carta_firmada_aprobada_user_id;
-- COMMIT;
