-- ═══════════════════════════════════════════════════════════════════════════
-- PROD · Restaurar `puesto_area_scope` (se botó antes de tiempo)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- QUÉ PASÓ
--   En prod se corrió `2026-08-25_puesto_una_sola_area.sql` COMPLETO, incluido
--   el PASO 5, que estaba comentado y con el aviso de correrlo solo DESPUÉS de
--   desplegar el backend. El backend que hoy corre en prod es del 21-ago y
--   todavía lee `puesto_area_scope`, así que toda consulta que la toca revienta:
--
--     * Configuración → Categorías y Puestos  (GET /api/v1/habilitacion/catalogos/admin)
--     * Solicitud de Personal                 (puestos filtrados por área del solicitante)
--     * Flujo FFT / pre-ingreso               (área del puesto pedido)
--
--   No es que falte un SQL: sobró uno. Este script deshace ese paso de más y
--   devuelve prod al estado en que quedó el PASO 4 del script original.
--
-- QUÉ SE RECUPERA Y QUÉ NO
--   El vínculo VIVO de cada puesto no se perdió: vive en `puesto.area_scope_id`
--   (118 puestos con área, 0 puestos eliminados con área), y de ahí se repuebla.
--   Lo que sí se perdió para siempre son los vínculos que ya estaban dados de
--   baja (state = false) y los `puesto_area_scope_id` originales. Nada apunta a
--   esa tabla por FK, así que no arrastra nada.
--
-- DESPUÉS DE ESTO
--   Correr el PASO 5 del script original recién cuando el backend ya lea
--   `puesto.area_scope_id` y esté desplegado. Mientras tanto la tabla y su
--   trigger se quedan.
--
-- Correr PASO por PASO en pgAdmin. Cada paso es idempotente.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- PASO 0 — Diagnóstico. No modifica nada.
-- ═══════════════════════════════════════════════════════════════════════════
-- Antes de correr los pasos siguientes tiene que salir: tabla 0, funcion 0,
-- trigger 0, puestos vivos con area 118. Si tabla sale 1, este script ya corrió.

SELECT 'tabla puesto_area_scope' AS chequeo,
       (SELECT count(*) FROM information_schema.tables
         WHERE table_schema = 'public' AND table_name = 'puesto_area_scope') AS valor
UNION ALL SELECT 'funcion puesto_area_scope_sync',
       (SELECT count(*) FROM pg_proc WHERE proname = 'puesto_area_scope_sync')
UNION ALL SELECT 'trigger trg_puesto_area_scope_sync',
       (SELECT count(*) FROM pg_trigger WHERE tgname = 'trg_puesto_area_scope_sync')
UNION ALL SELECT 'puestos vivos con area',
       (SELECT count(*) FROM puesto WHERE state AND area_scope_id IS NOT NULL)
UNION ALL SELECT 'puestos eliminados con area',
       (SELECT count(*) FROM puesto WHERE NOT state AND area_scope_id IS NOT NULL);


-- ═══════════════════════════════════════════════════════════════════════════
-- PASO 1 — Recrear la tabla, con la misma definición del script original.
-- ═══════════════════════════════════════════════════════════════════════════
-- Los ids arrancan de nuevo en 1: ninguna tabla referencia `puesto_area_scope`,
-- así que el id no significa nada fuera de ella.
--
-- Los tres índices son los que había: el UNIQUE parcial sobre las vivas (revivir
-- un vínculo en vez de duplicarlo), el índice por puesto y el índice por área.
-- Se suma `ux_puesto_area_scope_una_area`, el candado que puso el PASO 2 del
-- script del corte: un puesto no puede tener dos áreas vivas. Ojo con esto —
-- Configuración → Puestos todavía deja marcar varias áreas en pantalla, y con
-- el candado puesto ese guardado falla (23505) en vez de romper la regla en
-- silencio. Es a propósito.

BEGIN;

CREATE TABLE IF NOT EXISTS puesto_area_scope (
    puesto_area_scope_id integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puesto_id            integer     NOT NULL REFERENCES puesto(puesto_id),
    area_scope_id        integer     NOT NULL REFERENCES area_scope(area_scope_id),
    created_date_time    timestamptz NOT NULL DEFAULT now(),
    created_user_id      integer,
    updated_date_time    timestamptz,
    updated_user_id      integer,
    state                boolean     NOT NULL DEFAULT true
);

COMMENT ON TABLE puesto_area_scope IS
    'A que areas pertenece cada puesto. Recreada el 2026-08-25 tras botarla antes del deploy: el backend en prod todavia la lee. Desde el corte del 2026-08-25 el area real vive en puesto.area_scope_id y esta tabla es solo su espejo; se bota junto con su trigger cuando el codigo deje de leerla.';

CREATE UNIQUE INDEX IF NOT EXISTS ux_puesto_area_scope_vivo
    ON puesto_area_scope (puesto_id, area_scope_id) WHERE state;
CREATE INDEX IF NOT EXISTS ix_puesto_area_scope_puesto
    ON puesto_area_scope (puesto_id) WHERE state;
CREATE INDEX IF NOT EXISTS ix_puesto_area_scope_area
    ON puesto_area_scope (area_scope_id) WHERE state;
CREATE UNIQUE INDEX IF NOT EXISTS ux_puesto_area_scope_una_area
    ON puesto_area_scope (puesto_id) WHERE state;

COMMIT;


-- ═══════════════════════════════════════════════════════════════════════════
-- PASO 2 — Repoblar desde `puesto.area_scope_id`.
-- ═══════════════════════════════════════════════════════════════════════════
-- Una fila por puesto que tenga área. El `state` del vínculo copia el del
-- puesto: un puesto eliminado no puede figurar en un área viva (es la misma
-- regla que aplica EliminarPuestosAsync en el backend). Hoy no hay ninguno,
-- pero el script no depende de eso.
--
-- El NOT EXISTS lo hace idempotente: correrlo dos veces no duplica nada.

BEGIN;

INSERT INTO puesto_area_scope (puesto_id, area_scope_id, created_date_time, state)
SELECT p.puesto_id, p.area_scope_id, now(), p.state
  FROM puesto p
 WHERE p.area_scope_id IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM puesto_area_scope pas
                    WHERE pas.puesto_id = p.puesto_id
                      AND pas.area_scope_id = p.area_scope_id);

COMMIT;


-- ═══════════════════════════════════════════════════════════════════════════
-- PASO 3 — Recrear el trigger que mantiene las dos en sincronía.
-- ═══════════════════════════════════════════════════════════════════════════
-- Es el PASO 3 del script del corte, tal cual. Sin él, cada puesto que GTH cree
-- o edite desde Configuración graba el área SOLO en la intermedia y deja
-- `puesto.area_scope_id` en NULL: al día siguiente ese puesto sale «Sin área» y
-- nadie ata el cabo. Va después del PASO 2 a propósito, para no disparar 118
-- UPDATE que no cambian nada.

BEGIN;

CREATE OR REPLACE FUNCTION puesto_area_scope_sync() RETURNS trigger AS $$
DECLARE
    v_ids integer[];
BEGIN
    -- Con IF y no con un CASE dentro del UPDATE: en un DELETE el registro NEW
    -- no existe y plpgsql revienta con solo nombrarlo, aunque la rama no corra.
    IF    TG_OP = 'INSERT' THEN v_ids := ARRAY[NEW.puesto_id];
    ELSIF TG_OP = 'DELETE' THEN v_ids := ARRAY[OLD.puesto_id];
    ELSE  v_ids := ARRAY[OLD.puesto_id, NEW.puesto_id];  -- el UPDATE puede mover el vínculo de puesto
    END IF;

    UPDATE puesto p
       SET area_scope_id = (SELECT pas.area_scope_id
                              FROM puesto_area_scope pas
                             WHERE pas.puesto_id = p.puesto_id AND pas.state
                             LIMIT 1)
     WHERE p.puesto_id = ANY(v_ids);
    RETURN NULL;
END $$ LANGUAGE plpgsql;

COMMENT ON FUNCTION puesto_area_scope_sync() IS
    'TEMPORAL (2026-08-25): refleja puesto_area_scope en puesto.area_scope_id mientras el backend siga escribiendo la tabla intermedia. Se elimina junto con puesto_area_scope.';

DROP TRIGGER IF EXISTS trg_puesto_area_scope_sync ON puesto_area_scope;
CREATE TRIGGER trg_puesto_area_scope_sync
    AFTER INSERT OR UPDATE OR DELETE ON puesto_area_scope
    FOR EACH ROW EXECUTE FUNCTION puesto_area_scope_sync();

COMMIT;


-- ═══════════════════════════════════════════════════════════════════════════
-- PASO 4 — Verificación. Las dos primeras tienen que salir vacías.
-- ═══════════════════════════════════════════════════════════════════════════

-- 4a. Columna e intermedia dicen lo mismo, en los dos sentidos. 0 filas.
SELECT p.puesto_id, p.nombre, p.area_scope_id, pas.area_scope_id AS en_la_intermedia
FROM puesto p
LEFT JOIN puesto_area_scope pas ON pas.puesto_id = p.puesto_id AND pas.state
WHERE p.state AND p.area_scope_id IS DISTINCT FROM pas.area_scope_id;

-- 4b. Ningún puesto con más de un área viva. 0 filas.
SELECT puesto_id, count(*) FROM puesto_area_scope
WHERE state GROUP BY puesto_id HAVING count(*) > 1;

-- 4c. Conteos. `vinculos_vivos` tiene que ser 118, igual que `puestos_con_area`,
--     y el trigger tiene que estar en 1.
SELECT (SELECT count(*) FROM puesto_area_scope WHERE state)                    AS vinculos_vivos,
       (SELECT count(*) FROM puesto WHERE state AND area_scope_id IS NOT NULL) AS puestos_con_area,
       (SELECT count(*) FROM pg_trigger WHERE tgname = 'trg_puesto_area_scope_sync') AS trigger_puesto;

-- 4d. Lo mismo que arma la pantalla, para probar sin abrir el navegador.
--     Tiene que traer 302 puestos, 118 de ellos con área.
SELECT p.puesto_id, p.nombre, c.nombre AS categoria,
       coalesce(ai.area_item_name, '-- sin area --') AS area
FROM puesto p
JOIN categoria c                ON c.categoria_id = p.categoria_id
LEFT JOIN puesto_area_scope pas ON pas.puesto_id = p.puesto_id AND pas.state
LEFT JOIN area_scope s          ON s.area_scope_id = pas.area_scope_id AND s.state
LEFT JOIN area_item ai          ON ai.area_item_id = s.area_item_id AND ai.state
WHERE p.state
ORDER BY p.nombre;
