-- CORRIGE (reemplaza, no suma) el mapeo Plantilla -> Peligros de las 19 especialidades.
-- La migración 2026-09-30 (fusión de plantillas duplicadas) UNIÓ el set correcto recién
-- transcrito con el set viejo/genérico que esas plantillas ya traían desde antes de esta
-- sesión (todas con el catálogo completo de 23 peligros marcado) — por eso en el ATS de
-- Supervisión aparecían peligros de otras especialidades. Este script borra el mapeo de
-- las 19 plantillas y lo vuelve a insertar SOLO con lo que corresponde a su Excel real.

DELETE FROM ss_ats_plantilla_peligro
WHERE plantilla_id IN (
    SELECT id FROM ss_ats_plantilla WHERE nombre IN (
        'ATS Albañilería',
        'ATS Carpintería',
        'ATS Enchape',
        'ATS Limpieza de OT y Vecinos',
        'ATS Monitores',
        'ATS Pintura',
        'ATS Topografía',
        'ATS Vaciado',
        'ATS Vigías',
        'ATS Recepción y Traslado de Material',
        'ATS Izaje',
        'ATS Misceláneo',
        'ATS Supervisión',
        'ATS Llaveros',
        'ATS Concesionarias',
        'ATS Prelosas',
        'ATS Limpieza de Oficinas y Departamentos',
        'ATS Acarreo de Vidrios',
        'ATS Acero'
    )
);

INSERT INTO ss_ats_plantilla_peligro (plantilla_id, peligro_id)
SELECT pl.id, pe.id
FROM (VALUES
    ('ATS Albañilería', 'Ruido'),
    ('ATS Albañilería', 'Radiación solar'),
    ('ATS Albañilería', 'Trabajo a distinto nivel (altura)'),
    ('ATS Albañilería', 'Proyección de partículas (esquirlas )'),
    ('ATS Albañilería', 'Manipulación de escaleras'),
    ('ATS Albañilería', 'Disco en movimiento'),
    ('ATS Albañilería', 'Superficies cortantes'),
    ('ATS Albañilería', 'Superficies calientes'),
    ('ATS Albañilería', 'Energía eléctrica'),
    ('ATS Albañilería', 'Ductos y bordes de fachada'),
    ('ATS Albañilería', 'Partículas suspendidas (polvo)'),
    ('ATS Albañilería', 'Posturas forzadas'),
    ('ATS Albañilería', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Albañilería', 'Manipulación de herramientas manuales'),
    ('ATS Albañilería', 'Partes giratorias'),
    ('ATS Albañilería', 'Trabajos sobre cabeza'),
    ('ATS Albañilería', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Albañilería', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Albañilería', 'Cargas suspendidas'),
    ('ATS Albañilería', 'Sustancias químicas líquidas ( desmoldante, resinas, membranas, )'),
    ('ATS Albañilería', 'Uso de amoladora'),
    ('ATS Albañilería', 'Uso de rotomartillo'),
    ('ATS Carpintería', 'Ruido'),
    ('ATS Carpintería', 'Radiación solar'),
    ('ATS Carpintería', 'Trabajo a distinto nivel (altura)'),
    ('ATS Carpintería', 'Proyección de partículas (esquirlas de madera)'),
    ('ATS Carpintería', 'Manipulación de escaleras'),
    ('ATS Carpintería', 'Disco en movimiento'),
    ('ATS Carpintería', 'Superficies cortantes'),
    ('ATS Carpintería', 'Superficies calientes'),
    ('ATS Carpintería', 'Energía eléctrica'),
    ('ATS Carpintería', 'Ductos y bordes de fachada'),
    ('ATS Carpintería', 'Partículas suspendidas (polvo)'),
    ('ATS Carpintería', 'Posturas forzadas'),
    ('ATS Carpintería', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Carpintería', 'Manipulación de herramientas manuales'),
    ('ATS Carpintería', 'Partes giratorias'),
    ('ATS Carpintería', 'Trabajos sobre cabeza'),
    ('ATS Carpintería', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Carpintería', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Carpintería', 'Cargas suspendidas'),
    ('ATS Carpintería', 'Sustancias químicas líquidas ( desmoldante, resinas, membranas, )'),
    ('ATS Enchape', 'Ruido'),
    ('ATS Enchape', 'Radiación solar'),
    ('ATS Enchape', 'Trabajo a distinto nivel (altura)'),
    ('ATS Enchape', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Enchape', 'Manipulación de escaleras'),
    ('ATS Enchape', 'Disco en movimiento'),
    ('ATS Enchape', 'Superficies cortantes'),
    ('ATS Enchape', 'Superficies calientes'),
    ('ATS Enchape', 'Energía eléctrica'),
    ('ATS Enchape', 'Ductos y bordes de fachada'),
    ('ATS Enchape', 'Partículas suspendidas (polvo)'),
    ('ATS Enchape', 'Posturas forzadas'),
    ('ATS Enchape', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Enchape', 'Manipulación de herramientas manuales'),
    ('ATS Enchape', 'Partes giratorias'),
    ('ATS Enchape', 'Trabajos sobre cabeza'),
    ('ATS Enchape', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Enchape', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Enchape', 'Cargas suspendidas'),
    ('ATS Enchape', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Enchape', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Enchape', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Limpieza de OT y Vecinos', 'Ruido'),
    ('ATS Limpieza de OT y Vecinos', 'Radiación solar'),
    ('ATS Limpieza de OT y Vecinos', 'Trabajo a distinto nivel (altura)'),
    ('ATS Limpieza de OT y Vecinos', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Limpieza de OT y Vecinos', 'Manipulación de escaleras'),
    ('ATS Limpieza de OT y Vecinos', 'Manipulacion de sustancias quimicas'),
    ('ATS Limpieza de OT y Vecinos', 'Superficies cortantes'),
    ('ATS Limpieza de OT y Vecinos', 'Superficies calientes'),
    ('ATS Limpieza de OT y Vecinos', 'Energía eléctrica'),
    ('ATS Limpieza de OT y Vecinos', 'Ductos y bordes de fachada'),
    ('ATS Limpieza de OT y Vecinos', 'Partículas suspendidas (polvo)'),
    ('ATS Limpieza de OT y Vecinos', 'Posturas forzadas'),
    ('ATS Limpieza de OT y Vecinos', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Limpieza de OT y Vecinos', 'Manipulación de herramientas manuales'),
    ('ATS Limpieza de OT y Vecinos', 'Partes giratorias'),
    ('ATS Limpieza de OT y Vecinos', 'Trabajos sobre cabeza'),
    ('ATS Limpieza de OT y Vecinos', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Limpieza de OT y Vecinos', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Limpieza de OT y Vecinos', 'Cargas suspendidas'),
    ('ATS Limpieza de OT y Vecinos', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Limpieza de OT y Vecinos', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Limpieza de OT y Vecinos', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Monitores', 'Ruido'),
    ('ATS Monitores', 'Radiación solar'),
    ('ATS Monitores', 'Trabajo a distinto nivel (altura)'),
    ('ATS Monitores', 'Proyección de partículas (esquirlas de madera)'),
    ('ATS Monitores', 'Manipulación de escaleras'),
    ('ATS Monitores', 'Disco en movimiento'),
    ('ATS Monitores', 'Superficies cortantes'),
    ('ATS Monitores', 'Superficies calientes'),
    ('ATS Monitores', 'Energía eléctrica'),
    ('ATS Monitores', 'Ductos y bordes de fachada'),
    ('ATS Monitores', 'Partículas suspendidas (polvo)'),
    ('ATS Monitores', 'Posturas forzadas'),
    ('ATS Monitores', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Monitores', 'Manipulación de herramientas manuales'),
    ('ATS Monitores', 'Partes giratorias'),
    ('ATS Monitores', 'Trabajos sobre cabeza'),
    ('ATS Monitores', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Monitores', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Monitores', 'Cargas suspendidas'),
    ('ATS Monitores', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Monitores', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Monitores', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Pintura', 'Ruido'),
    ('ATS Pintura', 'Radiación solar'),
    ('ATS Pintura', 'Trabajo a distinto nivel (altura)'),
    ('ATS Pintura', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Pintura', 'Manipulación de escaleras'),
    ('ATS Pintura', 'Disco en movimiento'),
    ('ATS Pintura', 'Superficies cortantes'),
    ('ATS Pintura', 'Superficies calientes'),
    ('ATS Pintura', 'Energía eléctrica'),
    ('ATS Pintura', 'Ductos y bordes de fachada'),
    ('ATS Pintura', 'Partículas suspendidas (polvo)'),
    ('ATS Pintura', 'Posturas forzadas'),
    ('ATS Pintura', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Pintura', 'Manipulación de herramientas manuales'),
    ('ATS Pintura', 'Partes giratorias'),
    ('ATS Pintura', 'Trabajos sobre cabeza'),
    ('ATS Pintura', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Pintura', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Pintura', 'Cargas suspendidas'),
    ('ATS Pintura', 'Manipulación de balón de gas con soplete'),
    ('ATS Pintura', 'Manipulación de sustancias químicas (cemento y membranas y aditivos )'),
    ('ATS Pintura', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Topografía', 'Ruido'),
    ('ATS Topografía', 'Radiación solar'),
    ('ATS Topografía', 'Trabajo a distinto nivel (altura)'),
    ('ATS Topografía', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Topografía', 'Manipulación de escaleras'),
    ('ATS Topografía', 'Disco en movimiento'),
    ('ATS Topografía', 'Superficies cortantes'),
    ('ATS Topografía', 'Superficies calientes'),
    ('ATS Topografía', 'Energía eléctrica'),
    ('ATS Topografía', 'Ductos y bordes de fachada'),
    ('ATS Topografía', 'Partículas suspendidas (polvo)'),
    ('ATS Topografía', 'Posturas forzadas'),
    ('ATS Topografía', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Topografía', 'Manipulación de herramientas manuales'),
    ('ATS Topografía', 'Partes giratorias'),
    ('ATS Topografía', 'Trabajos sobre cabeza'),
    ('ATS Topografía', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Topografía', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Topografía', 'Cargas suspendidas'),
    ('ATS Topografía', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Topografía', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Topografía', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Vaciado', 'Ruido'),
    ('ATS Vaciado', 'Radiación solar'),
    ('ATS Vaciado', 'Trabajo a distinto nivel (altura)'),
    ('ATS Vaciado', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Vaciado', 'Manipulación de escaleras'),
    ('ATS Vaciado', 'Superficies calientes'),
    ('ATS Vaciado', 'Energía eléctrica'),
    ('ATS Vaciado', 'Ductos y bordes de fachada'),
    ('ATS Vaciado', 'Partículas suspendidas (polvo)'),
    ('ATS Vaciado', 'Posturas forzadas'),
    ('ATS Vaciado', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Vaciado', 'Manipulación de herramientas manuales'),
    ('ATS Vaciado', 'Partes giratorias'),
    ('ATS Vaciado', 'Trabajos sobre cabeza'),
    ('ATS Vaciado', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Vaciado', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Vaciado', 'Cargas suspendidas'),
    ('ATS Vaciado', 'Manipulación de balón de gas con soplete'),
    ('ATS Vaciado', 'Manipulación de sustancias químicas (cemento y membranas y aditivos )'),
    ('ATS Vaciado', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Vigías', 'Ruido'),
    ('ATS Vigías', 'Radiación solar'),
    ('ATS Vigías', 'Trabajo a distinto nivel (altura)'),
    ('ATS Vigías', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Vigías', 'Manipulación de escaleras'),
    ('ATS Vigías', 'Disco en movimiento'),
    ('ATS Vigías', 'Superficies cortantes'),
    ('ATS Vigías', 'Superficies calientes'),
    ('ATS Vigías', 'Energía eléctrica'),
    ('ATS Vigías', 'Ductos y bordes de fachada'),
    ('ATS Vigías', 'Partículas suspendidas (polvo)'),
    ('ATS Vigías', 'Posturas forzadas'),
    ('ATS Vigías', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Vigías', 'Manipulación de herramientas manuales'),
    ('ATS Vigías', 'Partes giratorias'),
    ('ATS Vigías', 'Trabajos sobre cabeza'),
    ('ATS Vigías', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Vigías', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Vigías', 'Cargas suspendidas'),
    ('ATS Vigías', 'Manipulación de balón de gas con soplete'),
    ('ATS Vigías', 'Manipulación de sustancias químicas (cemento y membranas y aditivos )'),
    ('ATS Vigías', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Vigías', 'Vehiculos externos y Peatones'),
    ('ATS Recepción y Traslado de Material', 'Ruido'),
    ('ATS Recepción y Traslado de Material', 'Radiación solar'),
    ('ATS Recepción y Traslado de Material', 'Trabajo a distinto nivel (altura)'),
    ('ATS Recepción y Traslado de Material', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Recepción y Traslado de Material', 'Manipulación de escaleras'),
    ('ATS Recepción y Traslado de Material', 'Disco en movimiento'),
    ('ATS Recepción y Traslado de Material', 'Superficies cortantes'),
    ('ATS Recepción y Traslado de Material', 'Superficies calientes'),
    ('ATS Recepción y Traslado de Material', 'Energía eléctrica'),
    ('ATS Recepción y Traslado de Material', 'Ductos y bordes de fachada'),
    ('ATS Recepción y Traslado de Material', 'Partículas suspendidas (polvo)'),
    ('ATS Recepción y Traslado de Material', 'Posturas forzadas'),
    ('ATS Recepción y Traslado de Material', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Recepción y Traslado de Material', 'Manipulación de herramientas manuales'),
    ('ATS Recepción y Traslado de Material', 'Partes giratorias'),
    ('ATS Recepción y Traslado de Material', 'Trabajos sobre cabeza'),
    ('ATS Recepción y Traslado de Material', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Recepción y Traslado de Material', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Recepción y Traslado de Material', 'Cargas suspendidas'),
    ('ATS Recepción y Traslado de Material', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Recepción y Traslado de Material', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Recepción y Traslado de Material', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Izaje', 'Ruido'),
    ('ATS Izaje', 'Radiación solar'),
    ('ATS Izaje', 'Trabajo a distinto nivel (altura)'),
    ('ATS Izaje', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Izaje', 'Manipulación de escaleras'),
    ('ATS Izaje', 'Disco en movimiento'),
    ('ATS Izaje', 'Superficies cortantes'),
    ('ATS Izaje', 'Superficies calientes'),
    ('ATS Izaje', 'Energía eléctrica'),
    ('ATS Izaje', 'Ductos y bordes de fachada'),
    ('ATS Izaje', 'Partículas suspendidas (polvo)'),
    ('ATS Izaje', 'Posturas forzadas'),
    ('ATS Izaje', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Izaje', 'Manipulación de herramientas manuales'),
    ('ATS Izaje', 'Partes giratorias'),
    ('ATS Izaje', 'Trabajos sobre cabeza'),
    ('ATS Izaje', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Izaje', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Izaje', 'Cargas suspendidas'),
    ('ATS Izaje', 'Manipulación de balón de gas con soplete'),
    ('ATS Izaje', 'Manipulación de sustancias químicas (cemento y membranas y aditivos )'),
    ('ATS Izaje', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Misceláneo', 'Ruido'),
    ('ATS Misceláneo', 'Radiación solar'),
    ('ATS Misceláneo', 'Trabajo a distinto nivel (altura)'),
    ('ATS Misceláneo', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Misceláneo', 'Manipulación de escaleras'),
    ('ATS Misceláneo', 'Disco en movimiento'),
    ('ATS Misceláneo', 'Superficies cortantes'),
    ('ATS Misceláneo', 'Superficies calientes'),
    ('ATS Misceláneo', 'Energía eléctrica'),
    ('ATS Misceláneo', 'Ductos y bordes de fachada'),
    ('ATS Misceláneo', 'Partículas suspendidas (polvo)'),
    ('ATS Misceláneo', 'Posturas forzadas'),
    ('ATS Misceláneo', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Misceláneo', 'Manipulación de herramientas manuales'),
    ('ATS Misceláneo', 'Partes giratorias'),
    ('ATS Misceláneo', 'Trabajos sobre cabeza'),
    ('ATS Misceláneo', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Misceláneo', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Misceláneo', 'Cargas suspendidas'),
    ('ATS Misceláneo', 'Manipulación de balón de gas con soplete'),
    ('ATS Misceláneo', 'Manipulación de sustancias químicas (cemento y membranas y aditivos )'),
    ('ATS Misceláneo', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Misceláneo', 'Traslado de obra a obra'),
    ('ATS Supervisión', 'Ruido'),
    ('ATS Supervisión', 'Radiación solar'),
    ('ATS Supervisión', 'Trabajo a distinto nivel (altura)'),
    ('ATS Supervisión', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Supervisión', 'Manipulación de escaleras'),
    ('ATS Supervisión', 'Disco en movimiento'),
    ('ATS Supervisión', 'Superficies cortantes'),
    ('ATS Supervisión', 'Superficies calientes'),
    ('ATS Supervisión', 'Energía eléctrica'),
    ('ATS Supervisión', 'Ductos y bordes de fachada'),
    ('ATS Supervisión', 'Partículas suspendidas (polvo)'),
    ('ATS Supervisión', 'Posturas forzadas'),
    ('ATS Supervisión', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Supervisión', 'Manipulación de herramientas manuales'),
    ('ATS Supervisión', 'Partes giratorias'),
    ('ATS Supervisión', 'Trabajos sobre cabeza'),
    ('ATS Supervisión', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Supervisión', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Supervisión', 'Cargas suspendidas'),
    ('ATS Supervisión', 'Subir y bajar escaleras de obra'),
    ('ATS Supervisión', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Supervisión', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Supervisión', 'Brillo de pantalla'),
    ('ATS Llaveros', 'Ruido'),
    ('ATS Llaveros', 'Trabajo a distinto nivel (altura)'),
    ('ATS Llaveros', 'Proyección de partículas(esquirlas)'),
    ('ATS Llaveros', 'Manipulación de escaleras'),
    ('ATS Llaveros', 'Disco en movimiento'),
    ('ATS Llaveros', 'Superficies cortantes'),
    ('ATS Llaveros', 'Energía eléctrica'),
    ('ATS Llaveros', 'Ductos y bordes de fachada'),
    ('ATS Llaveros', 'Partículas suspendidas (polvo)'),
    ('ATS Llaveros', 'Posturas forzadas'),
    ('ATS Llaveros', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Llaveros', 'Manipulación de herramientas manuales'),
    ('ATS Llaveros', 'Partes giratorias'),
    ('ATS Llaveros', 'Trabajos sobre cabeza'),
    ('ATS Llaveros', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Llaveros', 'Cargas suspendidas'),
    ('ATS Llaveros', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Llaveros', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Concesionarias', 'Ruido'),
    ('ATS Concesionarias', 'Proyección de partículas(esquirlas)'),
    ('ATS Concesionarias', 'Superficies cortantes'),
    ('ATS Concesionarias', 'Energía eléctrica'),
    ('ATS Concesionarias', 'Partículas suspendidas (polvo)'),
    ('ATS Concesionarias', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Concesionarias', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Concesionarias', 'Sismo'),
    ('ATS Concesionarias', 'Superficies calientes'),
    ('ATS Concesionarias', 'Acoso Sexual en el trabajo'),
    ('ATS Concesionarias', 'Microorganismos (virus, bacterias, hongos)'),
    ('ATS Concesionarias', 'Cargas suspendidas'),
    ('ATS Prelosas', 'Ruido'),
    ('ATS Prelosas', 'Radiación solar'),
    ('ATS Prelosas', 'Trabajo a distinto nivel (altura)'),
    ('ATS Prelosas', 'Proyección de partículas (esquirlas de madera)'),
    ('ATS Prelosas', 'Manipulación de escaleras'),
    ('ATS Prelosas', 'Disco en movimiento'),
    ('ATS Prelosas', 'Superficies cortantes'),
    ('ATS Prelosas', 'Superficies calientes'),
    ('ATS Prelosas', 'Energía eléctrica'),
    ('ATS Prelosas', 'Ductos y bordes de fachada'),
    ('ATS Prelosas', 'Partículas suspendidas (polvo)'),
    ('ATS Prelosas', 'Posturas forzadas'),
    ('ATS Prelosas', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Prelosas', 'Manipulación de herramientas manuales'),
    ('ATS Prelosas', 'Partes giratorias'),
    ('ATS Prelosas', 'Trabajos sobre cabeza'),
    ('ATS Prelosas', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Prelosas', 'Montaje de estructuras cerca, dentro o en el frontis de vecinos'),
    ('ATS Prelosas', 'Cargas suspendidas'),
    ('ATS Prelosas', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Prelosas', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Prelosas', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Ruido'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Radiación solar'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Trabajo a distinto nivel (uso de escaleras)'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Manipulacion de sustancias quimicas'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Superficies cortantes'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Energía eléctrica'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Partículas suspendidas (polvo)'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Movimientos repetitivos (barrer, limpiar)'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Manipulación de herramientas manuales'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Trabajos sobre cabeza'),
    ('ATS Limpieza de Oficinas y Departamentos', 'Piso húmedo o resbaladizo'),
    ('ATS Acarreo de Vidrios', 'Ruido'),
    ('ATS Acarreo de Vidrios', 'Radiación solar'),
    ('ATS Acarreo de Vidrios', 'Trabajo a distinto nivel (altura)'),
    ('ATS Acarreo de Vidrios', 'Proyección de partículas (esquirlas de concreto)'),
    ('ATS Acarreo de Vidrios', 'Trabajo a distinto nivel (uso de escaleras)'),
    ('ATS Acarreo de Vidrios', 'Manipulacion de sustancias quimicas'),
    ('ATS Acarreo de Vidrios', 'Superficies cortantes'),
    ('ATS Acarreo de Vidrios', 'Energía eléctrica'),
    ('ATS Acarreo de Vidrios', 'Partículas suspendidas (polvo)'),
    ('ATS Acarreo de Vidrios', 'Ductos y bordes de fachada'),
    ('ATS Acarreo de Vidrios', 'Posturas forzadas'),
    ('ATS Acarreo de Vidrios', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Acarreo de Vidrios', 'Manipulación de herramientas manuales'),
    ('ATS Acarreo de Vidrios', 'Partes giratorias'),
    ('ATS Acarreo de Vidrios', 'Trabajos sobre cabeza'),
    ('ATS Acarreo de Vidrios', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Acarreo de Vidrios', 'Cargas suspendidas'),
    ('ATS Acarreo de Vidrios', 'Traslado de materiales con apoyo de stocka (montacarga manual)'),
    ('ATS Acarreo de Vidrios', 'Piso húmedo o resbaladizo'),
    ('ATS Acarreo de Vidrios', 'Manipulación de materiales y/o herramientas en altura'),
    ('ATS Acarreo de Vidrios', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)'),
    ('ATS Acero', 'Ruido'),
    ('ATS Acero', 'Radiación solar'),
    ('ATS Acero', 'Trabajo a distinto nivel (altura)'),
    ('ATS Acero', 'Proyección de partículas (esquirlas de metal)'),
    ('ATS Acero', 'Manipulación de escaleras'),
    ('ATS Acero', 'Disco en movimiento'),
    ('ATS Acero', 'Superficies cortantes'),
    ('ATS Acero', 'Superficies calientes'),
    ('ATS Acero', 'Energía eléctrica'),
    ('ATS Acero', 'Ductos y bordes de fachada'),
    ('ATS Acero', 'Partículas suspendidas (polvo metalico)'),
    ('ATS Acero', 'Posturas forzadas'),
    ('ATS Acero', 'Manipulación manual de cargas (traslado, levantamiento)'),
    ('ATS Acero', 'Manipulación de herramientas manuales'),
    ('ATS Acero', 'Partes giratorias'),
    ('ATS Acero', 'Trabajos sobre cabeza'),
    ('ATS Acero', 'Tránsito de personas por acceso de la obra y/o escaleras fijas'),
    ('ATS Acero', 'Montaje de estructuras (andamios)'),
    ('ATS Acero', 'Cargas suspendidas'),
    ('ATS Acero', 'Maquinaria, equipos en movimiento (Volquetes, Excavadora, Minicargador, Camiones Mixer, faja transportadora, etc)')
) AS v(plantilla_nombre, peligro_nombre)
JOIN ss_ats_plantilla pl ON pl.nombre = v.plantilla_nombre
JOIN ss_ats_peligro pe ON pe.nombre = v.peligro_nombre
WHERE NOT EXISTS (
    SELECT 1 FROM ss_ats_plantilla_peligro pp WHERE pp.plantilla_id = pl.id AND pp.peligro_id = pe.id
);