-- Rediseño de Penalidades: se desacopla de RAC (ver Features/SsomaModule/PenalidadFeature).
-- Aplicar a mano contra la BD (psql/pgAdmin), NO via `dotnet ef database update`.
--
-- No se borra la tabla vieja: se archiva con un rename. Las penalidades que hoy existan ahí
-- nunca pasaron por el flujo de aprobación nuevo (Residente/Gerencia), así que no se migran
-- automáticamente al nuevo pipeline — quedan como archivo histórico consultable, y si alguna
-- sigue abierta en la práctica, se vuelve a registrar en Penalidades bajo el proceso nuevo.

-- IF EXISTS porque en esta base la tabla puede no haberse llegado a crear nunca (las migraciones
-- EF de este repo no se aplican con `dotnet ef database update` — ver convención del proyecto);
-- si no existe, esto no hace nada y sigue con la creación de las tablas nuevas.
ALTER TABLE IF EXISTS ssoma_rac_penalidad RENAME TO ssoma_rac_penalidad_legacy;

CREATE TABLE IF NOT EXISTS ssoma_penalidad (
    id                            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                        text NOT NULL,

    origen_tipo                   text NOT NULL DEFAULT 'DIRECTO',
    origen_id                     integer NULL,

    empresa_id                    integer NOT NULL,
    proyecto_id                   integer NOT NULL,
    infraccion_id                 integer NOT NULL,
    severidad                     text NOT NULL,

    monto_calculado               numeric NOT NULL DEFAULT 0,
    monto_final                   numeric NULL,
    monto_ajustado_motivo         text NULL,
    uit_referencia                numeric NOT NULL DEFAULT 0,

    descripcion_ocurrido          text NULL,

    estado                        text NOT NULL DEFAULT 'Registrada',

    plazo_descargo_horas          integer NOT NULL DEFAULT 48,
    plazo_descargo_vence_en       timestamp with time zone NULL,
    descargo_por_incomparecencia  boolean NOT NULL DEFAULT false,

    aprobado_residente_por_id     integer NULL,
    aprobado_residente_en         timestamp with time zone NULL,
    motivo_rechazo_residente      text NULL,

    aprobado_gerencia_por_id      integer NULL,
    aprobado_gerencia_en          timestamp with time zone NULL,
    motivo_rechazo_gerencia       text NULL,

    descargo_texto                text NULL,
    documento_url                  text NULL,
    descargo_fecha                 timestamp with time zone NULL,
    descargo_usuario_id            integer NULL,

    argumento_ssoma                text NULL,
    recomendacion_ssoma            text NULL,
    evaluado_por_ssoma_id          integer NULL,
    evaluado_ssoma_en              timestamp with time zone NULL,

    resolucion_texto               text NULL,
    resolucion_tipo                text NULL,
    motivo_objecion_gerencia       text NULL,
    resuelto_por_id                integer NULL,
    resuelta_en                    timestamp with time zone NULL,

    pdf_notificacion_url           text NULL,
    pdf_resolucion_url             text NULL,

    created_by                     integer NULL,
    created_at                     timestamp with time zone NOT NULL DEFAULT now(),
    updated_at                     timestamp with time zone NULL,

    CONSTRAINT fk_ssoma_penalidad_infraccion
        FOREIGN KEY (infraccion_id) REFERENCES ssoma_rac_infraccion (id)
);

CREATE INDEX IF NOT EXISTS ix_ssoma_penalidad_empresa_id  ON ssoma_penalidad (empresa_id);
CREATE INDEX IF NOT EXISTS ix_ssoma_penalidad_proyecto_id ON ssoma_penalidad (proyecto_id);
CREATE INDEX IF NOT EXISTS ix_ssoma_penalidad_estado      ON ssoma_penalidad (estado);
CREATE INDEX IF NOT EXISTS ix_ssoma_penalidad_origen      ON ssoma_penalidad (origen_tipo, origen_id);

CREATE TABLE IF NOT EXISTS ssoma_penalidad_estado_historial (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    penalidad_id      integer NOT NULL,
    estado_anterior   text NULL,
    estado_nuevo      text NOT NULL,
    cambio_date_time  timestamp with time zone NOT NULL,
    cambio_user_id    integer NULL,
    created_date_time timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT fk_ssoma_penalidad_estado_historial_penalidad
        FOREIGN KEY (penalidad_id) REFERENCES ssoma_penalidad (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_ssoma_penalidad_estado_historial_penalidad_id
    ON ssoma_penalidad_estado_historial (penalidad_id);

-- El seed de datos (infracciones + UIT) vive aparte, en
-- Migrations_Manual/2026-09-09_seed_infracciones_sst.sql — correr ese script después de este.
