-- Fase 2 de Penalidades: apelación post-"Aplicada" (una sola vez, evidencia nueva, directo a
-- Gerencia) + historial de "gestión previa" por empresa (correos/cartas/reuniones antes de
-- penalizar). Aplicar a mano (psql/pgAdmin), después de las migraciones de Fase 1. Idempotente.

ALTER TABLE ssoma_penalidad
    ADD COLUMN IF NOT EXISTS apelacion_usada           boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS plazo_apelacion_dias       integer NOT NULL DEFAULT 5,
    ADD COLUMN IF NOT EXISTS plazo_apelacion_vence_en   timestamp with time zone NULL,
    ADD COLUMN IF NOT EXISTS apelacion_texto            text NULL,
    ADD COLUMN IF NOT EXISTS apelacion_documento_url    text NULL,
    ADD COLUMN IF NOT EXISTS apelacion_fecha            timestamp with time zone NULL,
    ADD COLUMN IF NOT EXISTS apelacion_usuario_id       integer NULL;

CREATE TABLE IF NOT EXISTS ssoma_gestion_previa_empresa (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id        integer NOT NULL,
    proyecto_id       integer NULL,
    tipo              text NOT NULL,
    fecha             timestamp with time zone NOT NULL,
    descripcion       text NOT NULL,
    adjunto_url       text NULL,
    registrado_por_id integer NULL,
    created_at        timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ssoma_gestion_previa_empresa_empresa_id
    ON ssoma_gestion_previa_empresa (empresa_id);
