-- ============================================================================
-- Gestion GTH - Solicitud de Personal -> Configuracion -> Visibilidad
--
-- Que areas ve cada trabajador en Solicitud de Personal. Sin filas vivas manda
-- el algoritmo de siempre (su area y lo que cuelga de ella; GTH y el Gerente
-- General ven todo). Con filas vivas mandan las areas marcadas, y lo que el
-- usuario registro el mismo lo sigue viendo siempre.
--
-- ORDEN DE EJECUCION: ANTES del deploy del backend (o junto con el). El backend
-- nuevo consulta esta tabla en cada carga de Solicitud de Personal: si se
-- despliega sin ella, la pantalla responde 500. El backend viejo no la usa, asi
-- que correrlo antes no rompe nada.
--
-- Idempotente: se puede correr varias veces. Aplicar en dev y prod.
-- Sin tildes a proposito: psql las manda en cp1252 y revienta la conexion.
-- ============================================================================

BEGIN;

-- -- 1) Tabla ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_solicitud_personal_visibilidad_area (
    gth_solicitud_personal_visibilidad_area_id integer GENERATED BY DEFAULT AS IDENTITY,
    worker_id         integer     NOT NULL,
    area_scope_id     integer     NOT NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_solicitud_personal_visibilidad_area
        PRIMARY KEY (gth_solicitud_personal_visibilidad_area_id),
    CONSTRAINT fk_gth_solicitud_personal_visibilidad_area_worker
        FOREIGN KEY (worker_id) REFERENCES workers (id),
    CONSTRAINT fk_gth_solicitud_personal_visibilidad_area_area_scope
        FOREIGN KEY (area_scope_id) REFERENCES area_scope (area_scope_id)
);

-- Una sola fila viva por trabajador y area. Tambien es el indice con el que se
-- leen las areas de un trabajador (worker_id va primero).
CREATE UNIQUE INDEX IF NOT EXISTS ux_gth_solicitud_personal_visibilidad_area_vivo
    ON gth_solicitud_personal_visibilidad_area (worker_id, area_scope_id)
    WHERE state = true;

COMMENT ON TABLE gth_solicitud_personal_visibilidad_area IS
    'Configuracion propia de que areas ve cada trabajador en Solicitud de Personal (Configuracion -> Visibilidad). Con filas vivas reemplaza al algoritmo (su area + subarbol; GTH y GG ven todo). Marcar el arbol entero es ver todo. Solo cuentan las fichas activas.';

-- -- 2) feature --------------------------------------------------------------
-- El module_id se hereda de la pantalla en vez de buscar el modulo por texto.
INSERT INTO feature (feature_key, module_id)
SELECT 'gestion-gth.config.visibilidad-solicitud-personal', f.module_id
FROM feature f
WHERE f.feature_key = 'gestion-gth.solicitud-personal'
  AND NOT EXISTS (
      SELECT 1 FROM feature x
      WHERE x.feature_key = 'gestion-gth.config.visibilidad-solicitud-personal');

-- -- 3) role_feature ---------------------------------------------------------
-- Los mismos roles que ya administran la Configuracion de Solicitud de Personal
-- (sus correos), mas ADMINISTRADOR DEL SISTEMA (1). Quien mas la necesite se
-- agrega desde Seguridad -> Roles.
INSERT INTO role_feature (role_id, feature_id)
SELECT rf.role_id, nueva.feature_id
FROM feature nueva
JOIN feature base ON base.feature_key = 'gestion-gth.reclutamiento.configuracion'
JOIN role_feature rf ON rf.feature_id = base.feature_id
WHERE nueva.feature_key = 'gestion-gth.config.visibilidad-solicitud-personal'
ON CONFLICT (role_id, feature_id) DO NOTHING;

INSERT INTO role_feature (role_id, feature_id)
SELECT 1, f.feature_id
FROM feature f
WHERE f.feature_key = 'gestion-gth.config.visibilidad-solicitud-personal'
ON CONFLICT (role_id, feature_id) DO NOTHING;

COMMIT;

-- -- Verificacion ------------------------------------------------------------
-- SELECT f.feature_id, f.feature_key, r.role_id, r.role_description
-- FROM feature f
-- LEFT JOIN role_feature rf ON rf.feature_id = f.feature_id
-- LEFT JOIN role r ON r.role_id = rf.role_id
-- WHERE f.feature_key = 'gestion-gth.config.visibilidad-solicitud-personal';
