-- Bancos: catálogo propio con CRUD (Configuración → Bancos) y el banco de cada razón social.
--
-- Por qué:
--   • El formulario de bienvenida del colaborador le pregunta si quiere que se le abra su cuenta
--     sueldo, y el banco NO lo elige él: lo define la razón social con la que se le contrata
--     (Aquitania trabaja con Scotiabank, Eco Vital con el BCP, etc.). Ese dato no existía en
--     ninguna parte, así que la pregunta no se podía formular sin hardcodear la tabla de
--     equivalencias en el código.
--   • El banco va normalizado en su propia tabla (y no como texto en `contributor`) porque es un
--     dato predefinido que se repite entre razones sociales: cambiarle el nombre a un banco tiene
--     que ser una fila, no un UPDATE masivo.
--   • Solo las razones sociales del grupo (`es_abril`) tienen banco: a un contratista o proveedor
--     no se le abre cuenta sueldo a nadie. Lo garantiza un CHECK, no solo la pantalla.
--
-- ORDEN DE DESPLIEGUE: este script va ANTES de subir el código. El backend nuevo lee
-- `contributor.banco_id` en el catálogo de razones sociales y sirve `/api/v1/configuracion/bancos`,
-- así que sin la tabla y la columna esas dos pantallas responden 500. Al revés no pasa nada: el
-- código viejo ignora lo que este script agrega.
--
-- Re-corrible: cada bloque revisa el estado antes de escribir.

BEGIN;

-- ── 1. Catálogo de bancos ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS banco (
    banco_id          integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_banco PRIMARY KEY (banco_id)
);

-- Un solo banco vivo por código y por nombre: el soft delete deja filas repetidas con state=false,
-- así que los únicos van filtrados (misma regla que el resto de los catálogos del sistema).
CREATE UNIQUE INDEX IF NOT EXISTS ix_banco_codigo_vivo
    ON banco (codigo) WHERE state = true;
CREATE UNIQUE INDEX IF NOT EXISTS ix_banco_nombre_vivo
    ON banco (lower(btrim(nombre))) WHERE state = true;

-- Los cuatro con los que opera el grupo hoy. El resto se dan de alta desde la pantalla.
INSERT INTO banco (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES
    ('BCP',        'Banco de Crédito del Perú (BCP)', 1),
    ('BBVA',       'BBVA',                            2),
    ('SCOTIABANK', 'Scotiabank',                      3),
    ('BANBIF',     'BanBif',                          4)
) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM banco b WHERE b.codigo = v.codigo AND b.state = true);

-- ── 2. Banco de la razón social ─────────────────────────────────────────────
ALTER TABLE contributor
    ADD COLUMN IF NOT EXISTS banco_id integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'contributor'::regclass AND conname = 'fk_contributor_banco'
    ) THEN
        ALTER TABLE contributor
            ADD CONSTRAINT fk_contributor_banco
            FOREIGN KEY (banco_id) REFERENCES banco (banco_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_contributor_banco_id
    ON contributor (banco_id) WHERE banco_id IS NOT NULL;

-- ── 3. Solo las razones sociales del grupo llevan banco ─────────────────────
-- Va VALIDATED (sin NOT VALID) a propósito: en este punto ninguna fila tiene banco_id, así que
-- validar las filas existentes es trivial y no hay riesgo de bloquear la tabla.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'contributor'::regclass AND conname = 'ck_contributor_banco_solo_abril'
    ) THEN
        ALTER TABLE contributor
            ADD CONSTRAINT ck_contributor_banco_solo_abril
            CHECK (banco_id IS NULL OR es_abril);
    END IF;
END $$;

-- ── 4. Banco de cada razón social del grupo ─────────────────────────────────
-- El mapeo lo dio GTH. Se empareja por un trozo del nombre y no por id porque los ids de
-- `contributor` no son los mismos en dev y en producción; los patrones se escriben SIN letras
-- acentuadas ('ncipe de paz', 'a de oro') para que calcen igual esté o no tildado el nombre
-- guardado. Solo escribe las que todavía no tienen banco: si alguien ya lo corrigió desde la
-- pantalla, este script no lo deshace.
UPDATE contributor c
SET banco_id = b.banco_id,
    updated_date_time = now()
FROM (VALUES
    ('aquitania',    'SCOTIABANK'),
    ('a de oro',     'BANBIF'),      -- Bahia / Bahía de oro
    ('campitelli',   'SCOTIABANK'),
    ('carpi',        'SCOTIABANK'),
    ('eco vital',    'BCP'),
    ('ncipe de paz', 'BCP'),         -- Corporación Inmobiliaria Príncipe de Paz
    ('la vid',       'BBVA'),
    ('lares',        'SCOTIABANK'),
    ('marsella',     'SCOTIABANK'),
    ('naresh',       'SCOTIABANK'),
    ('salerno',      'BCP'),
    ('seshat',       'BCP'),
    ('verbo',        'BBVA')
) AS v(patron, banco_codigo)
JOIN banco b ON b.codigo = v.banco_codigo AND b.state = true
WHERE c.state = true
  AND c.es_abril = true
  AND c.banco_id IS NULL
  AND lower(c.contributor_name) LIKE '%' || v.patron || '%';

-- ── 5. Feature de la pantalla Configuración → Bancos ────────────────────────
-- Mismo módulo que el resto de Configuración y los MISMOS roles que ya administran razones
-- sociales: quien mantiene las razones sociales es quien mantiene sus bancos.
INSERT INTO feature (feature_key, module_id)
SELECT 'configuracion.bancos', f.module_id
FROM feature f
WHERE f.feature_key = 'configuracion.companies'
  AND NOT EXISTS (SELECT 1 FROM feature x WHERE x.feature_key = 'configuracion.bancos');

INSERT INTO role_feature (role_id, feature_id)
SELECT rf.role_id, nueva.feature_id
FROM role_feature rf
JOIN feature f     ON f.feature_id = rf.feature_id AND f.feature_key = 'configuracion.companies'
CROSS JOIN feature nueva
WHERE nueva.feature_key = 'configuracion.bancos'
ON CONFLICT (role_id, feature_id) DO NOTHING;

COMMIT;
