-- ============================================================================
-- Firma personal por TIPO: dibujada con el mouse o subida como imagen.
--
-- Antes la firma de una persona era UNA sola y vivía en tres columnas de
-- `person` (signature_image_bytes / signature_mime / signature_updated_date_time),
-- siempre dibujada en un canvas. Ahora una persona puede tener registrada una
-- firma POR CADA TIPO, y Consolidados exige la del tipo que esté habilitado en
-- Consolidados → Configuración → Firmas.
--
-- Guardar dos tipos en `person` habría significado duplicar las tres columnas
-- (y otras tres el día que aparezca un tercer tipo), así que la firma pasa a su
-- propia tabla con FK al catálogo de tipos.
--
-- Re-corrible: todo es IF NOT EXISTS / ON CONFLICT DO NOTHING.
--
-- ⚠️ El Paso 6 (DROP de las columnas viejas de `person`) va SOLO DESPUÉS de
--    desplegar el backend nuevo. Corriéndolo junto con el resto, el backend que
--    está vivo en ese momento todavía lee esas columnas y se cae.
-- ============================================================================

BEGIN;

-- ── Paso 1: catálogo de tipos de firma ──────────────────────────────────────
-- `active` = el tipo se ofrece al firmar. Hoy lo honra únicamente Consolidados
-- (los dos checkboxes de su Configuración); Contabilidad y "Tu firma" siguen
-- ofreciendo solo el dibujo, así que un tipo inactivo NO les cambia nada.
CREATE TABLE IF NOT EXISTS firma_tipo (
    id                integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            varchar(20) NOT NULL,
    nombre            varchar(80) NOT NULL,
    active            boolean     NOT NULL DEFAULT true,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    state             boolean     NOT NULL DEFAULT true
);

-- Un solo tipo vivo por código (los dados de baja se conservan para auditoría).
CREATE UNIQUE INDEX IF NOT EXISTS ux_firma_tipo_codigo
    ON firma_tipo (codigo) WHERE state;

INSERT INTO firma_tipo (codigo, nombre)
VALUES ('DIBUJO', 'Dibujo con el mouse'),
       ('IMAGEN', 'Imagen subida')
ON CONFLICT DO NOTHING;

-- ── Paso 2: la firma de cada persona, una por tipo ──────────────────────────
CREATE TABLE IF NOT EXISTS person_firma (
    id                integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id         integer     NOT NULL REFERENCES person(person_id),
    firma_tipo_id     integer     NOT NULL REFERENCES firma_tipo(id),
    -- Siempre PNG: el backend normaliza a PNG lo que se suba (JPG/WEBP incluidos)
    -- porque es lo único que el estampador del PDF dibuja con transparencia.
    image_bytes       bytea       NOT NULL,
    mime              varchar(50) NOT NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    state             boolean     NOT NULL DEFAULT true
);

-- Una sola firma viva por persona y tipo: volver a registrar reemplaza la fila.
CREATE UNIQUE INDEX IF NOT EXISTS ux_person_firma_vigente
    ON person_firma (person_id, firma_tipo_id) WHERE state;

-- La consulta caliente es "las firmas vivas de esta persona" (al firmar y al
-- abrir el panel), y `person` se alcanza desde `app_user` por person.user_id.
CREATE INDEX IF NOT EXISTS ix_person_firma_person
    ON person_firma (person_id) WHERE state;

-- ── Paso 3: mudar las firmas que ya existen ─────────────────────────────────
-- Todas las registradas hasta hoy se dibujaron en el canvas, así que entran
-- como DIBUJO. Sin esto, todo el que ya tenía firma volvería a ver el modal.
INSERT INTO person_firma (person_id, firma_tipo_id, image_bytes, mime,
                          created_date_time, updated_date_time)
SELECT p.person_id,
       ft.id,
       p.signature_image_bytes,
       COALESCE(p.signature_mime, 'image/png'),
       COALESCE(p.signature_updated_date_time, now()),
       p.signature_updated_date_time
FROM person p
CROSS JOIN firma_tipo ft
WHERE p.signature_image_bytes IS NOT NULL
  AND ft.codigo = 'DIBUJO'
  AND ft.state
ON CONFLICT DO NOTHING;

-- ── Paso 4: funcionalidad de la sección "Firmas" ────────────────────────────
-- Cuelga del mismo módulo que el resto de la configuración de Consolidados.
INSERT INTO feature (feature_key, module_id)
SELECT 'gestion-administrativa.config.firmas', f.module_id
FROM feature f
WHERE f.feature_key = 'gestion-administrativa.config.consolidadores-areas'
ON CONFLICT (feature_key) DO NOTHING;

-- ── Paso 5: los mismos roles que ya administran Consolidados ────────────────
INSERT INTO role_feature (role_id, feature_id)
SELECT rf.role_id, nueva.feature_id
FROM role_feature rf
JOIN feature actual ON actual.feature_id = rf.feature_id
CROSS JOIN feature nueva
WHERE actual.feature_key = 'gestion-administrativa.config.consolidadores-areas'
  AND nueva.feature_key  = 'gestion-administrativa.config.firmas'
ON CONFLICT DO NOTHING;

COMMIT;

-- ── Verificación ────────────────────────────────────────────────────────────
-- Los Pasos 4 y 5 son INSERT … SELECT: si la feature de la que copian no existiera,
-- insertarían 0 filas sin avisar y la sección quedaría invisible. Esto lo delata.
SELECT 'tipos de firma' AS que, count(*) AS filas FROM firma_tipo WHERE state
UNION ALL
SELECT 'firmas migradas', count(*) FROM person_firma WHERE state
UNION ALL
SELECT 'feature Firmas (debe ser 1)', count(*)
  FROM feature WHERE feature_key = 'gestion-administrativa.config.firmas'
UNION ALL
SELECT 'roles con acceso (debe ser >= 1)', count(*)
  FROM role_feature rf
  JOIN feature f ON f.feature_id = rf.feature_id
 WHERE f.feature_key = 'gestion-administrativa.config.firmas';

-- ============================================================================
-- ⚠️ PASO 6 — SOLO DESPUÉS DE DESPLEGAR EL BACKEND NUEVO
--
-- Las tres columnas dejan de capturarse en el Paso 3: el dato ya vive completo
-- en `person_firma` y la auditoría es de filas, no de columnas. Pero mientras
-- el backend viejo siga arriba las sigue leyendo (mi-firma, facturas de
-- Contabilidad, carta oferta de GTH), así que este bloque va aparte.
--
-- ALTER TABLE person DROP COLUMN signature_image_bytes;
-- ALTER TABLE person DROP COLUMN signature_mime;
-- ALTER TABLE person DROP COLUMN signature_updated_date_time;
-- ============================================================================
