-- ─────────────────────────────────────────────────────────────────────────────
-- Alcance de rendición: hasta qué mes hacia atrás se pueden rendir las salidas.
--
-- Hasta ahora la regla estaba escrita en el código: durante los N días hábiles del mes siguiente
-- se podía rendir EL MES ANTERIOR y nada más. Ahora ese "hasta dónde" es configurable desde
-- Solicitud de Salidas → Configuración → Días reembolsables, con dos ajustes:
--   • alcance_plazo_id      → cuánto alcanza la ventana de los N días hábiles.
--   • alcance_permanente_id → cuánto alcanza en cualquier momento del mes. NULL = no aplica.
--     Cuando está puesto, manda sobre el anterior.
-- Los valores por defecto (plazo = "Hasta el mes anterior", permanente = NULL) dejan el sistema
-- comportándose exactamente como antes.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ga_rendicion_alcance (
    ga_rendicion_alcance_id integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                  varchar(50)  NOT NULL,
    nombre                  varchar(150) NOT NULL,
    -- Meses hacia atrás que abarca, contados desde el mes en curso. 1 = el mes anterior.
    meses_atras             integer      NOT NULL,
    orden                   integer      NOT NULL DEFAULT 0,
    active                  boolean      NOT NULL DEFAULT true,
    state                   boolean      NOT NULL DEFAULT true,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz,
    CONSTRAINT ck_ga_rendicion_alcance_meses CHECK (meses_atras >= 1 AND meses_atras <= 120)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_rendicion_alcance_codigo
    ON ga_rendicion_alcance (lower(codigo)) WHERE state;

INSERT INTO ga_rendicion_alcance (ga_rendicion_alcance_id, codigo, nombre, meses_atras, orden)
SELECT v.id, v.codigo, v.nombre, v.meses, v.orden
FROM (VALUES
    (1, 'MES_ANTERIOR', 'Hasta el mes anterior', 1, 1),
    (2, 'SEIS_MESES',   'Hasta 6 meses atrás',   6, 2)
) AS v(id, codigo, nombre, meses, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM ga_rendicion_alcance a WHERE lower(a.codigo) = lower(v.codigo) AND a.state
);

-- La identidad queda por detrás de los ids sembrados a mano.
SELECT setval(
    pg_get_serial_sequence('ga_rendicion_alcance', 'ga_rendicion_alcance_id'),
    (SELECT COALESCE(MAX(ga_rendicion_alcance_id), 1) FROM ga_rendicion_alcance));

ALTER TABLE ga_rendicion_config
    ADD COLUMN IF NOT EXISTS alcance_plazo_id      integer,
    ADD COLUMN IF NOT EXISTS alcance_permanente_id integer;

-- Las filas que ya existen se quedan con el comportamiento de antes.
UPDATE ga_rendicion_config SET alcance_plazo_id = 1 WHERE alcance_plazo_id IS NULL;

ALTER TABLE ga_rendicion_config
    ALTER COLUMN alcance_plazo_id SET DEFAULT 1,
    ALTER COLUMN alcance_plazo_id SET NOT NULL;

ALTER TABLE ga_rendicion_config DROP CONSTRAINT IF EXISTS fk_ga_rendicion_config_alcance_plazo;
ALTER TABLE ga_rendicion_config DROP CONSTRAINT IF EXISTS fk_ga_rendicion_config_alcance_permanente;

ALTER TABLE ga_rendicion_config
    ADD CONSTRAINT fk_ga_rendicion_config_alcance_plazo
        FOREIGN KEY (alcance_plazo_id)      REFERENCES ga_rendicion_alcance (ga_rendicion_alcance_id),
    ADD CONSTRAINT fk_ga_rendicion_config_alcance_permanente
        FOREIGN KEY (alcance_permanente_id) REFERENCES ga_rendicion_alcance (ga_rendicion_alcance_id);
