-- Onboarding: el correo de bienvenida y el «Formulario - Nuevos Talentos» que lleva adentro.
--
-- Qué cambia:
--   • Se va la actividad «Informar al cliente interno la fecha de ingreso confirmada»: ese aviso ya
--     lo manda Reclutamiento al solicitante cuando el colaborador finaliza su carta oferta
--     (CARTA_OFERTA_FINALIZADA), así que acá era pedir dos veces lo mismo.
--   • ENVIAR_BIENVENIDA pasa a llamarse «Enviar correo de bienvenida» y deja de ser un rótulo: le
--     abre al colaborador su formulario web y le manda el enlace.
--   • Nace `gth_onboarding_formulario`, el reemplazo del Microsoft Forms «Nuevos Talentos». No
--     vuelve a preguntar lo que el formulario del postulante ya capturó (nombre, documento, fecha
--     de nacimiento, celular, distrito, estado civil, estudios): pregunta lo que recién existe
--     ahora que la persona entra —domicilio, condiciones pactadas, cuenta sueldo, tallas, contacto
--     de emergencia, renta de 5ta y la fecha de su EMO—.
--   • Sus catálogos van en tablas y no como texto: ubicación de trabajo, talla de calzado y el
--     estado del certificado de renta de 5ta.
--
-- ORDEN DE DESPLIEGUE: este script va ANTES de subir el código; también necesita
-- `banco_y_razon_social.sql`, que es de donde sale el banco que el formulario le muestra al
-- colaborador. Sin estas tablas la bandeja de Onboarding responde 500.
--
-- Re-corrible: cada bloque revisa el estado antes de escribir.

BEGIN;

-- ── 1. Checklist: se va «Informar al cliente interno» ───────────────────────
UPDATE gth_onboarding_actividad
SET state = false, active = false, updated_date_time = now()
WHERE codigo = 'INFORMAR_CLIENTE_INTERNO' AND state = true;

-- ── 2. «Enviar correo de bienvenida» ────────────────────────────────────────
UPDATE gth_onboarding_actividad
SET nombre = 'Enviar correo de bienvenida',
    descripcion = 'Le abre su formulario de nuevos talentos y le manda el enlace junto con los '
                  || 'documentos normativos y la fecha límite.',
    orden = 1,
    updated_date_time = now()
WHERE codigo = 'ENVIAR_BIENVENIDA' AND state = true;

-- El aviso al responsable de obra queda segundo: la actividad del medio se dio de baja.
UPDATE gth_onboarding_actividad
SET orden = 2, updated_date_time = now()
WHERE codigo = 'AVISO_OBRA' AND state = true AND orden <> 2;

-- ── 3. Catálogo: ubicación de trabajo ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS gth_onboarding_ubicacion (
    gth_onboarding_ubicacion_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_onboarding_ubicacion PRIMARY KEY (gth_onboarding_ubicacion_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_onboarding_ubicacion_codigo_vivo
    ON gth_onboarding_ubicacion (codigo) WHERE state = true;

INSERT INTO gth_onboarding_ubicacion (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES
    ('OFICINA_PRINCIPAL', 'Oficina Principal', 1),
    ('PROYECTOS_ABRIL',   'Proyectos Abril',   2),
    ('SALAS_VENTAS',      'Salas de Ventas',   3)
) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM gth_onboarding_ubicacion u WHERE u.codigo = v.codigo AND u.state = true);

-- ── 4. Catálogo: talla de calzado ───────────────────────────────────────────
-- Aparte de `talla` (XS…XXL, la de la camisa): son dos escalas distintas y mezclarlas dejaría un
-- desplegable de botas ofreciendo "L".
CREATE TABLE IF NOT EXISTS talla_calzado (
    talla_calzado_id  integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_talla_calzado PRIMARY KEY (talla_calzado_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_talla_calzado_codigo_vivo
    ON talla_calzado (codigo) WHERE state = true;

INSERT INTO talla_calzado (codigo, nombre, orden)
SELECT n::text, n::text, n - 34
FROM generate_series(35, 44) AS n
WHERE NOT EXISTS (
    SELECT 1 FROM talla_calzado t WHERE t.codigo = n::text AND t.state = true);

-- ── 5. Catálogo: certificado de renta de 5ta categoría ──────────────────────
CREATE TABLE IF NOT EXISTS gth_renta_quinta (
    gth_renta_quinta_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_renta_quinta PRIMARY KEY (gth_renta_quinta_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_renta_quinta_codigo_vivo
    ON gth_renta_quinta (codigo) WHERE state = true;

INSERT INTO gth_renta_quinta (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES
    ('ENTREGADO',
     'Sí, ya lo entregué/entregaré en los documentos solicitados por correo.', 1),
    ('NO_APLICA',
     'No tengo dicho documento porque no entro en esta categoría.', 2),
    ('PENDIENTE_EMPLEADOR',
     'Sí, está pendiente de entrega por mi antiguo empleador; ni bien lo reciba lo envío.', 3)
) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM gth_renta_quinta r WHERE r.codigo = v.codigo AND r.state = true);

-- ── 6. Catálogo: estado del formulario de bienvenida ────────────────────────
CREATE TABLE IF NOT EXISTS gth_onboarding_formulario_estado (
    gth_onboarding_formulario_estado_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_onboarding_formulario_estado PRIMARY KEY (gth_onboarding_formulario_estado_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_onboarding_formulario_estado_codigo_vivo
    ON gth_onboarding_formulario_estado (codigo) WHERE state = true;

INSERT INTO gth_onboarding_formulario_estado (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES
    ('ENVIADO',    'Enviado',    1),
    ('COMPLETADO', 'Completado', 2)
) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM gth_onboarding_formulario_estado e WHERE e.codigo = v.codigo AND e.state = true);

-- ── 7. El formulario del nuevo colaborador ──────────────────────────────────
CREATE TABLE IF NOT EXISTS gth_onboarding_formulario (
    gth_onboarding_formulario_id integer GENERATED BY DEFAULT AS IDENTITY,
    gth_onboarding_id                   integer NOT NULL,
    token                               text    NOT NULL,
    gth_onboarding_formulario_estado_id integer NOT NULL,

    -- Envío del correo de bienvenida
    correo_envio      text        NOT NULL,
    fecha_limite      date,
    enviado_date_time timestamptz,
    enviado_user_id   integer,
    completado_date_time timestamptz,

    -- Datos personales
    direccion text,

    -- Información laboral (lo que el colaborador confirma del correo de bienvenida)
    puesto_id                   integer,
    fecha_ingreso               date,
    remuneracion_mensual        numeric(12,2),
    gth_onboarding_ubicacion_id integer,
    contributor_id              integer,

    -- Pago de haberes: el banco lo define la razón social, acá solo va su respuesta
    cuenta_sueldo boolean,

    -- Información personal complementaria
    sexo_id             integer,
    contacto_emergencia text,
    celular_emergencia  text,
    numero_hijos        integer,
    talla_calzado_id    integer,
    talla_id            integer,
    usa_lentes          boolean,
    hobbies             text,

    -- Renta de 5ta categoría y EMO de entrada
    gth_renta_quinta_id integer,
    fecha_emo           date,

    -- Consentimiento
    declaracion_veracidad boolean,

    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,

    CONSTRAINT pk_gth_onboarding_formulario PRIMARY KEY (gth_onboarding_formulario_id),
    CONSTRAINT fk_gof_onboarding  FOREIGN KEY (gth_onboarding_id)
        REFERENCES gth_onboarding (gth_onboarding_id),
    CONSTRAINT fk_gof_estado      FOREIGN KEY (gth_onboarding_formulario_estado_id)
        REFERENCES gth_onboarding_formulario_estado (gth_onboarding_formulario_estado_id),
    CONSTRAINT fk_gof_puesto      FOREIGN KEY (puesto_id)      REFERENCES puesto (puesto_id),
    CONSTRAINT fk_gof_ubicacion   FOREIGN KEY (gth_onboarding_ubicacion_id)
        REFERENCES gth_onboarding_ubicacion (gth_onboarding_ubicacion_id),
    CONSTRAINT fk_gof_contributor FOREIGN KEY (contributor_id) REFERENCES contributor (contributor_id),
    CONSTRAINT fk_gof_sexo        FOREIGN KEY (sexo_id)        REFERENCES sexo (sexo_id),
    CONSTRAINT fk_gof_talla_calzado FOREIGN KEY (talla_calzado_id)
        REFERENCES talla_calzado (talla_calzado_id),
    CONSTRAINT fk_gof_talla       FOREIGN KEY (talla_id)       REFERENCES talla (talla_id),
    CONSTRAINT fk_gof_renta_quinta FOREIGN KEY (gth_renta_quinta_id)
        REFERENCES gth_renta_quinta (gth_renta_quinta_id),
    CONSTRAINT ck_gof_numero_hijos CHECK (numero_hijos IS NULL OR numero_hijos >= 0)
);

-- Un solo formulario vivo por onboarding, y el token es la única credencial de la página pública:
-- no puede repetirse entre los vigentes.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_onboarding_formulario_onboarding_vivo
    ON gth_onboarding_formulario (gth_onboarding_id) WHERE state = true;
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_onboarding_formulario_token_vivo
    ON gth_onboarding_formulario (token) WHERE state = true;

-- ── 8. Correo configurable de bienvenida ────────────────────────────────────
-- El destinatario principal es SIEMPRE el colaborador; Configuración solo suma principales y
-- copias (mismo patrón que CARTA_OFERTA y FORMULARIO_ENVIO).
INSERT INTO gth_correo_tipo
    (codigo, nombre, descripcion, orden, principal_automatico, principal_automatico_active,
     principal_automatico_nombre, active, state)
SELECT 'ONB_BIENVENIDA',
       'Correo de bienvenida al colaborador',
       'Le da la bienvenida al nuevo colaborador y le manda el enlace de su formulario de nuevos '
       || 'talentos, la documentación que tiene que enviar y la fecha límite. Sale desde el '
       || 'checklist de Onboarding, con un clic de GTH.',
       COALESCE((SELECT MAX(orden) FROM gth_correo_tipo), 0) + 1,
       true, true, 'Colaborador', true, true
WHERE NOT EXISTS (
    SELECT 1 FROM gth_correo_tipo t WHERE t.codigo = 'ONB_BIENVENIDA' AND t.state = true);

COMMIT;
